<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction','profile');
?>
<div class="container min_height">
	<div class="row">
		<div class="col-md-8">
		<?php if(isset($this->vatTData) && count($this->vatTData)){
			  foreach($this->vatTData as $links){
				$id=$links->u_id;
		?>
			<div class="panel panel-default hover_body">			
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<a href="<?php echo $baseUrl;?>/profile-user?uid=<? echo base64_encode($id."-143"); ?>"><button type="button" class="btn btn-primary btn-sm" >View More </button></a></div>
					<div class="media-left"> 
					<?php if(isset($links->user_photo) && $links->user_photo!= ""){?>
						<img alt="" src="<?php echo $basePath?>/images/<?php echo $links->user_photo;?>" style="width:140px;height:150px;">
						<?php } else{?>
						<img class="img_pic" alt="" src="<? echo $basePath; ?>/images/480px-No_Image_Available.png" />
						<?php }?>
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="<?php echo $baseUrl;?>/profile-user/<?php echo $id;?>"><?php if(isset($links->username) && $links->username != ""){echo  $links->username;}else{ echo 'N/A';}?></a></h4>
						<p><span class="dim">City : </span> <?php if(isset($links->c_name) && $links->c_name != ""){echo  ucfirst($links->c_name);}else{ echo 'N/A';}?></p>
						<p><span class="dim">Languages : </span>Industry Name</p>
						<p><span class="dim">Skills :</span><?php  if(isset($links->skills) && $links->skills != ""){ echo  $links->skills;}else{echo 'N/A';}?></p>	
					</div>					
					<?php
					$string=$links->message;					
					$string = strip_tags($string);
					if (strlen($string) > 300) {
						$stringCut = substr($string, 0, 300);
						$string = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
					}
					?>
					<p><?php echo $string; ?></p>	
					</div>
				</div>
				
			</div>
			<?php }} else { ?>
							<br/>&nbsp;There are no userslist.
					<? }?>
			<div align="center">
				<?php				
					echo $this->paginationControl(
					$this->vatTData,
					'sliding',
					array('partial/paginator.phtml', 'Application'),
					array(
						'route' => 'user',
						'id' =>$this->id
						)
					);
				?>
			</div>			
			</div>
		<div class="col-md-4">
			<?php include('right-side-bar.phtml');?>
		</div>
	</div>
	</div>
