<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction','profile');
?>
<div class="container min_height">
	<div class="row">
		<div class="col-md-8">
		<?php if(isset($this->vatTData) && count($this->vatTData)>0){
			  foreach($this->vatTData as $links){
				$id=$links->u_id;
		?>
			<div class="panel panel-default hover_body">			
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<a href="<?php echo $baseUrl;?>/profile-user?uid=<? echo base64_encode($id."-143"); ?>"><button type="button" class="btn btn-primary btn-sm" >View More </button></a></div>
					<div class="media-left"> 
					<?php if(isset($links->user_photo) && $links->user_photo!= ""){?>						
						<img alt="" src="<?php echo $links->user_photo;?>" style="width:140px;height:150px;">
						<?php } else{ if(isset($links->gender) && $links->gender=='male'){ ?>
							<img style="width:140px;height:150px;" alt="" src="<? echo $basePath; ?>/images/480px-No_Image_Available.png" />
						<?php } else { ?>
							<img style="width:140px;height:150px;" alt="" src="<? echo $basePath; ?>/images/heroine_female.png" />
						<?php } ?>
						<?php }?>
					</div> 
					<div class="media-body" style="margin:0"> 
				<h4 class="media-heading"><a href="<?php echo $baseUrl;?>/profile-user?uid=<? echo base64_encode($id."-143"); ?>"><?php if(isset($links->username) && $links->username != ""){echo  ucfirst($links->username);}else{ echo 'N/A';}?></a></h4>
						<p><span class="dim">City : </span> <?php if(isset($links->c_name) && $links->c_name != ""){echo  ucfirst($links->c_name);}else{ echo 'N/A';}?></p>
						<p><span class="dim">Languages : </span>
							<?php 	
								if(isset($links->languages) && $links->languages!=""){
$testAll = $this->plugin('profile_helper')->userInformation(trim($links->languages,","));
									$lName = "";
									$lang_names = "";    
									foreach($testAll['langNames'] as $key=>$langs){
										$lang_names .= ucfirst($langs.', ');
										$lName = rtrim($lang_names, ', ');
									}
									echo $lName;
								}else{
									echo "N/A";
								}
							?>
						</p>
						<p><span class="dim">Skills :</span>
						<?php  
							$skills = $this->plugin('profile_helper')->userSkills($links->user_id);
							if(isset($skills) && count($skills)>=1)
							{
								$sName = "";
								$skill_names = "";    
								foreach($skills as $skill){
									$skill_names .= ucfirst($skill['u_category_name'].', ');
									$sName = rtrim($skill_names, ', ');
								}
								echo $sName;
							}
							else
							{ 
								echo 'N/A';
							}							
						?>							
						</p>	
						<?php
					if(isset($links->message) && $links->message!="") { 		
						$string= $links->message; 					
						$string = strip_tags($string);
						if (strlen($string) > 300) {
							$stringCut = substr($string, 0, 300);
							$string = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
						}
					?>
					<p> <span class="dim">More information : </span> <?php echo $string; ?></p>	
					<?php } else {?>
						<p> <span class="dim">More information : </span> N/A </p>	
					<?php } ?>
					</div>					
					
					</div>
				</div>
				
			</div>
			<?php }} else { ?>
							<br/>&nbsp;There are no userslist.
					<? }?>
			<div align="center">
				<?php				
					echo $this->paginationControl(
					$this->vatTData,
					'sliding',
					array('partial/paginator.phtml', 'Profiles'),
					array(
						'route' => 'all-profiles',
						'id' =>$this->id
						)
					);
				?>
			</div>			
			</div>
		<div class="col-md-4">
			<div class="">
			<div class="" align="center">
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- rightbanner -->
				<ins class="adsbygoogle"
					 style="display:inline-block;width:300px;height:250px"
					 data-ad-client="ca-pub-9408213208791031"
					 data-ad-slot="6451237032"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
			</div>
			<div class="">
			<div class="" align="center">
				<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<!-- rightbanner -->
				<ins class="adsbygoogle"
					 style="display:inline-block;width:300px;height:250px"
					 data-ad-client="ca-pub-9408213208791031"
					 data-ad-slot="6451237032"></ins>
				<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
			</div>	
			<?php include('right-side-bar.phtml');?>
			
		</div>
	</div>
	</div>
