<div class="container min_height">
	<div class="row">
		<div class="col-md-9">
		<form action="" method="POST"  onsubmit="return validate();" enctype="multipart/form-data" name="form" >		
				<div class="col-md-3 ">
					<div class="">
					<?php if(isset($this->allTests->user_photo) && $this->allTests->user_photo != ""){?>
					<img alt="" src="<?php echo $baseUrl;?>/<?php echo $this->allTests->user_photo?>" style="width:160px;height:160px;">
					<?php }else{ ?>						
						<img class="img_pic" alt="" src="<? echo $basePath; ?>/images/480px-No_Image_Available.png" />
					<?php }?>					
					</div>
					<input type="hidden" id="hid_user_photo" name="hid_user_photo" value="<?php echo $this->allTests->user_photo; ?>">
				<div class="text-center" style="padding-top:10px;">	
					<label class="btn-file">
					<input type="file" name="fileToUpload" id="image_file" class="form-control file_pad" style="height:auto">
					</label>	
					</div>					
				  </div>
					 <div class="col-md-9">				  
                    <div class="form-group row">					
                      <label class="col-sm-3 form-control-label">Full Name <span style="color:red">*</span></label>
                      <div class="col-sm-8">
                        <input type="text" class="form-control" readonly name="fname" id="fname" value="<?php if(isset($this->allTests->username) && $this->allTests->username != ""){echo  ucfirst($this->allTests->username); }?>">
                      </div>
					  <div><span id="f_name" style="color:red;"></span></div>
                    </div>
					<div class="form-group row">
                      <label class="col-sm-3 form-control-label" >Email <span style="color:red">*</span></label>
                      <div class="col-sm-8">
                        <input type="Email" class="form-control" readonly value="<?php if(isset($this->allTests->email) && $this->allTests->email != ""){echo  $this->allTests->email;}?>" name="email" id="email">
                      </div>
					  <div><span id="e_mail" style="color:red;"></span></div>
                    </div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" >Phone 
					 Number <span style="color:red">*</span></label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" value="<?php if(isset($this->allTests->contact_number) && $this->allTests->contact_number != ""){echo  $this->allTests->contact_number;}?>" name="phno" id="phno" onblur="return validy();">
                      </div>					  
					  <div class="col-sm-4">					  
					<label class="c-input c-radio">
					  <input id="radio1" name="ph" id="ph" type="radio" value="public" checked <?php if(isset($this->allTests->ph_pub_pri) && $this->allTests->ph_pub_pri == "public"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Public 
					</label>
					<label class="c-input c-radio">
					  <input id="radio2" name="ph" id="ph" type="radio" value="private" <?php if(isset($this->allTests->ph_pub_pri) && $this->allTests->ph_pub_pri == "private"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Private
					</label>
					</div>
					<div class="col-sm-10">
						<div class="text-center">						
						<h6 id="ph_no" style="color:red;"></h6>
						</div>
						
					</div>
				</div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" >Work</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" onblur="return validy();" value="<?php if(isset($this->allTests->work_phone) && $this->allTests->work_phone != ""){echo  $this->allTests->work_phone;}?>" name="work" id="work">
                      </div>
					  <div class="col-sm-4">
					  
					<label class="c-input c-radio">
					  <input id="work_phno1" name="work_phno" type="radio" value="public" checked <?php if(isset($this->allTests->work_pub_pri) && $this->allTests->work_pub_pri == "public"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Public 
					</label>
					<label class="c-input c-radio">
					  <input id="work_phno2" name="work_phno" type="radio" value="private" <?php if(isset($this->allTests->work_pub_pri) && $this->allTests->work_pub_pri == "private"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Private
					</label>
					</div>
					<div class="col-sm-10">
						<div class="text-center">						
						<h6 id="ph_work" style="color:red;"></h6>
						</div>
						
					</div>
				</div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" >Home</label>
                      <div class="col-sm-4">
                        <input type="text" class="form-control" onblur="return validy();" value="<?php if(isset($this->allTests->home_phone) && $this->allTests->home_phone != ""){echo  $this->allTests->home_phone;}?>" name="home" id="home">
                      </div>
					  <div class="col-sm-4">
					  
					<label class="c-input c-radio">
					  <input id="home_phno1" name="home_phno" type="radio" value="public" checked <?php if(isset($this->allTests->home_pub_pri) && $this->allTests->home_pub_pri == "public"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Public 
					</label>
					<label class="c-input c-radio">
					  <input id="home_phno2" name="home_phno" type="radio" value="private" <?php if(isset($this->allTests->home_pub_pri) && $this->allTests->home_pub_pri == "private"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Private
					</label>
					</div>
					<div class="col-sm-10">
						<div class="text-center">						
						<h6 id="ph_home" style="color:red;"></h6>
						</div>
						
					</div>
				</div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" >Gender <span style="color:red">*</span></label>                      
					  <div class="col-sm-4">					  
					<label class="c-input c-radio">
					  <input id="male" name="gender" type="radio" value="male" checked <?php if(isset($this->allTests->gender) && $this->allTests->gender == "male"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Male 
					</label>
					<label class="c-input c-radio">
					  <input id="female" name="gender" type="radio" value="female" <?php if(isset($this->allTests->gender) && $this->allTests->gender == "female"){echo  'checked';}?>>
					  <span class="c-indicator"></span>
					  Female
					</label>
					</div>
				</div>
				
				<div class="form-group row">
                      <label class="col-sm-3 form-control-label" >City <span style="color:red">*</span></label>
					   <div class="col-sm-8">
                       <select name="city" id="city" class="form-control" onblur="return validy();">
						<option value="default">Select city</option>
					   <?php foreach($this->cities as $city){ 
						if($city->c_id == $this->allTests->city) { ?>
						  <option value="<?php echo $city->c_id; ?>" selected="selected"><?php echo ucfirst($city->c_name); ?></option>  
					  <?php  } else{ ?>
						 <option value="<?php echo $city->c_id; ?>" ><?php echo ucfirst($city->c_name); ?></option>  
					  <?php } }?>
                       </select>
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="c_ity" style="color:red;"></h6>
						</div>						
					</div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" >Languages <span style="color:red">*</span></label>
                      <div class="col-sm-8">
                       <select name="lang[]" id="lang" multiple="multiple" class="form-control" onblur="return validy();">
						<option value="default">Select languages</option>
					   <?php 
						$str = $this->allTests->languages;
						$expoldeData = explode(',',$str);
						$lan = $expoldeData;
						foreach($this->lang as $language){							
							if(in_array($language->lan_id,$lan)){
								$lSele  = "selected";
							}else{
								$lSele  = "";
							}
					   ?>
						<option value="<?php echo $language->lan_id; ?>" <?php echo $lSele; ?>><?php echo ucfirst($language->lang_name); ?></option>
					   <?php }?>
                       </select>
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="l_ang" style="color:red;"></h6>
						</div>
						
					</div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label">Skills <span style="color:red">*</span></label>
                      <div class="col-sm-8">
						
                        <select class="form-control" id="state_id" name="state_id[]" multiple="multiple" onblur="return validy();">
						<option value="default" >Select skills</option>	
							<?php
								$res =''; $i=0;	
								foreach($this->skill as $result)
								{
									 $res[$i]=$result->us_u_c_id;
									 $i++;
								}	
							?>
							<?php 							
								if(isset($this->allSkills)){
									foreach($this->allSkills as $skills){							
										if(in_array($skills->u_c_id,$res))
										{
											$selected = 'selected';
										}
										else{
											$selected = '';
									}							
							?>				
								<option value="<?php echo $skills->u_c_id;?>" <?php echo $selected;?>>
								<?php echo $skills->u_category_name?></option>
							<?php } } ?>							
						</select>
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="s_kill" style="color:red;"></h6>
						</div>						
					</div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label">Face Book Profile Link <span style="color:red">*</span></label>
                      <div class="col-sm-8">
                        <input type="text" class="form-control" value="<?php if(isset($this->allTests->fb_profile_link) && $this->allTests->fb_profile_link != ""){echo  $this->allTests->fb_profile_link;}?>" name="fb" id="fb" onblur="return validy();">
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="f_b" style="color:red;"></h6>
						</div>						
					</div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label">Pics Upload</label>
                      <div class="col-sm-8">
						 <label class="btn btn-primary	 btn-file">
							Browse <input type="file" style="display: none;" name="images[]" multiple="multiple">
						</label>
                      </div>
                 </div>
				 <input type="hidden" name="hid_value" id="hid_value" value="<?php if(isset($this->videos) && !empty($this->videos)){ echo count($this->videos)-1;}else{ echo "0"; }?> ">
				  <div class="form-group row input_fields_wrap">							
                      <label class="col-sm-3 form-control-label">Video links</label>
					  <div id="addmore">
					<?php
						if(isset($this->videos) && !empty($this->videos)){
							$i = 0;									
							foreach($this->videos as $video){ ?>
							<div id="dyDiv<?php echo $i; ?>">
							<?php if($i!=0){ ?>
							<label class="col-sm-3 form-control-label">&nbsp;&nbsp;</label>
							<?php } ?>
						<div class="col-sm-8">
					  <div class="row">
						<div class="col-xs-10">						
						<div class="my-form">   
							<p class="text-box">										
				<input type="text" class="form-control" value="<?php echo $video->v_video_link; ?>" name="video[]" id="video<?php echo $i;?>"/>									
			<?php if($i==0){ ?>
<a style=" margin-left: 100%;position:absolute;margin-top:-13%;" href="javascript:void(0);" class="btn btn-primary" onclick="addMore()"> <span class="glyphicon glyphicon-plus"></span> </a>
			<?php  } else { ?>
<a style=" margin-left: 100%;position:absolute;margin-top:-13%;" href="javascript:void(0);" class="btn btn-primary" onclick="delVideo('<?php echo $i;?>')" ><span class="glyphicon glyphicon-minus"></span> </a>
			<?php } ?>
							</p>
						<div class="clearfix"></div>
						</div>						
                      </div> 
                      </div> 
                      </div> 							
                      </div> 							
					<?php $i++;} }else{ ?>	
                      <div class="col-sm-8">
					  <div class="row">
						<div class="col-xs-10">						
						<div class="my-form">   
							<p class="text-box">										
				<input type="text" class="form-control" value="" name="video[]" id="video0"/>									
							<a style=" margin-left: 100%;position:absolute;margin-top:-13%;" href="javascript:void(0);" class="btn btn-primary" onclick="addMore()"> <span class="glyphicon glyphicon-plus"></span> </a>
							</p>
						<div class="clearfix"></div>
						</div>						
                      </div> 
                      </div> 
                      </div> 
						<?php } ?>
					</div>	
				 <input type="hidden" id="hid_u_id" name="hid_u_id" value="<?php echo $this->allTests->u_id; ?>">		 
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" >More Information</label>
                      <div class="col-sm-8">
                       <textarea class="form-control" rows="3" id="comment"  name="msg"><?php if(isset($this->allTests->message) && $this->allTests->message != ""){echo  $this->allTests->message;}?></textarea>
					   <p style="font-size:13px">[Describe yourself 300 words]</p>
                      </div>
                 </div>				 
				  <div class="form-group row">
                      <label class="col-sm-3 form-control-label">&nbsp</label>
                      <div class="col-sm-8">
                        <input type="submit" class=" btn btn-primary" value="Update" name="submit"/>
                      </div>
                 </div>
		</div>
		</div>
		
		</form>
		</div>
		<div class="col-md-3">
			<img width="100%" alt="sfadda.com" src="http://localhost/video-collections/trunk/public/img/adsleft.jpg">		
		</div>
	</div>
</div>
								

<script type="text/javascript">
jQuery(document).ready(function($){
    $('.my-form .add-box').click(function(){
        var n = $('.text-box').length + 1;
        var box_html = $('<p class="text-box"><input type="text" class="form-control" name="video[]" value="" id="box' + n + '" /> <a href="#" class="remove-box">Remove</a></p>');
        box_html.hide();
        $('.my-form p.text-box:last').after(box_html);
        box_html.fadeIn('slow');
        return false;
    });
});
</script>
<script>
$('.my-form').on('click', '.remove-box', function(){    
    $(this).parent().fadeOut("slow", function() {
        $(this).remove();
        $('.box-number').each(function(index){
            $(this).text( index + 1 );
        });
    });
    return false;
});

function validate(){
	var name= document.getElementById('fname').value;
	var email= document.getElementById('email').value;
	var phno= document.getElementById('phno').value;		
	var city= document.getElementById('city').value;
	var state_id= document.getElementById('state_id').value;
	var lang= document.getElementById('lang').value;
	var work= document.getElementById('work').value;	
	var home= document.getElementById('home').value;
	var fb= document.getElementById('fb').value;
	var ename=/^[a-zA-Z]+$/;
	var eexp=/^[a-z0-9._]+@+[a-z0-9]+.+[a-z]{2,4}/;
	var moble=/^[0-9]/;	
	if(!name.match(ename) && name == "")
	{
		document.getElementById("f_name").innerHTML="Please enter full name";
		document.getElementById("fname").focus();
		return false;
	}
	if(!email.match(eexp) && email == "")
	{
		document.getElementById("e_mail").innerHTML="Please enter email";
		document.getElementById("email").focus();
		return false;
	}
	if(!phno.match(moble) || phno == "" || phno.length != 10)
	{
		document.getElementById("ph_no").innerHTML="Please enter valid phone  number";
		document.getElementById("phno").focus();
		return false;
	}
	
	if(work  != "")
	{
		
		if(!work.match(moble) ||   work.length != 10)
		{
			document.getElementById("ph_work").innerHTML="Please enter valid phone  number";
			document.getElementById("work").focus();
			return false;
		}
	}
	if(home  != "")
	{
		if(!home.match(moble) ||  home.length != 10)
		{
			document.getElementById("ph_home").innerHTML="Please enter valid phone  number";
			document.getElementById("home").focus();
			return false;
		}
	}
	if ((form.ph[0].checked == false ) && ( form.ph[1].checked == false ) )
	{
		alert ( "Please choose Public or Private for your contact number" );
		return false;
	}
	if ((form.gender[0].checked == false ) && ( form.gender[1].checked == false ) )
	{
		alert ( "Please choose gender" );
		return false;
	}
	if(city == "default")			
	{
		document.getElementById("c_ity").innerHTML="Please select city";
		return false;
	}
	if(lang == "default")			
	{
		document.getElementById("l_ang").innerHTML="Please select languages";
		return false;
	}
	if(state_id == "default")			
	{
		document.getElementById("s_kill").innerHTML="Please select skills";
		return false;
	}
	if(fb == "")
	{
	document.getElementById("f_b").innerHTML="Please enter facebook profile link";
		return false;	
	}
}
 function validy()
{
	document.getElementById("ph_no").innerHTML="";
	document.getElementById("ph_work").innerHTML="";
	document.getElementById("ph_home").innerHTML="";
	document.getElementById("c_ity").innerHTML="";
	document.getElementById("l_ang").innerHTML="";
	document.getElementById("s_kill").innerHTML="";
	document.getElementById("f_b").innerHTML="";
} 
$(document).ready(function() {
    var flag=true;
    $('#image_file').bind('change', function() {
        if($('#image_file').val()!=""){
        var val = $('#image_file').val();
            switch(val.substring(val.lastIndexOf('.') + 1).toLowerCase()){
                case 'gif': case 'jpg': case 'png': case 'jpeg':
                    flag=true;
                    break;
                default:
                    $(this).val('');
                    alert('Please Upload Valid Formats');
                    flag=false;
                    break;
            }
        }
        if(flag==true){
            if(this.files[0].size > 1000141){
                $("#fileerror").val(1);
                alert("Image size should be below 1 MB");
                return false;
            }
            else
            {
                $("#fileerror").val(0);
            }
        }
    });
});
function addMore(){
	if($("#video"+$('#hid_value').val()).val()==""){
		alert("Required");
		$("#video"+$('#hid_value').val()).focus();
		return false;
	}else{
		var html ="";
		var value = parseInt($('#hid_value').val())+1;
		html +='<div id="dyDiv'+value+'"><label class="col-sm-3 form-control-label">&nbsp;&nbsp;</label>';
		html +='<div class="col-sm-8"><div class="row">';
		html +='<div class="col-xs-10"><div class="my-form">';
		html +='<p class="text-box">';
		html +='<input type="text" class="form-control" value="" name="video[]" id="video'+value+'">';
		html +='<a style=" margin-left: 100%;position:absolute;margin-top:-13%;" href="javascript:void(0);" class="btn btn-primary" onclick="delVideo('+value+')" ><span class="glyphicon glyphicon-minus"></span> </a>';
		html +='</p><div class="clearfix"></div></div></div></div></div></div>';
		$('#addmore').append(html);							
		$('#hid_value').val(value);
	}
}
function delVideo(value){
	if($("#video"+value).val()==""){
		$('#dyDiv'+value).remove();
		$('#hid_value').val(parseInt(value)-1);
	}else{
		if (confirm("Are you sure?")){
			$('#dyDiv'+value).remove();
			$('#hid_value').val(parseInt(value)-1);
		}
	}	
}
</script>