<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction','profile');
?>
<div class="container min_height">
	<div class="row">
		<div class="col-md-8">
		<?php if(isset($this->vatTData) && count($this->vatTData)){
			//print_r($this->allTests);exit;
			  foreach($this->vatTData as $links){
				$id=$links->c_name;
				?>
			<div class="panel panel-default hover_body">			
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<a href="<?php echo $baseUrl;?>/profile-user/<?php echo $id;?>"><button type="button" class="btn btn-primary btn-sm" >View More </button></a></div>
					<div class="media-left"> 
					<?php if($links->user_photo != ""){?>
						<img alt="" src="<?php echo $baseUrl?>/<?php echo $links->user_photo;?>" style="width:140px;height:150px;">
						<?php } else{?>
						<img alt="" src="<?php echo $basePath?>/images/480px-No_Image_Available.png" style="width:140px;height:150px;">
						<?php }?>
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="<?php echo $baseUrl;?>/profile-user/<?php echo $id;?>"><?php if(isset($links->first_name) && $links->first_name != ""){echo  $links->first_name;  }else{ echo 'N/A';}?></a></h4>
						<p><span class="dim">City : </span> <?php if(isset($links->city) && $links->city != ""){echo  $links->c_name;}else{ echo 'N/A';}?></p>
						<p><span class="dim">Languages: </span>Industry Name</p>
						<p><span class="dim">Skills :</span><?php  if(isset($links->skills) && $links->skills != ""){ echo  $links->skills;}else{echo 'N/A';}?></p>	
					</div>
					
					<?php
					//echo $baseUrl;exit;
					$string=$links->message;					
					$string = strip_tags($string);
					if (strlen($string) > 300) {
						//$a=$row["news_id"];
						//$b=$row['category_id'];
						$stringCut = substr($string, 0, 300);
						$string = substr($stringCut, 0, strrpos($stringCut, ' ')).'... 
						<a href="'.$baseUrl.'/profile-user/'.$id.'">View More</a>'; 
					}
					?>
					<p><?php echo $string; ?></p>	
					</div>
				</div>
				
			</div>
			<?php }} else { ?>
							<br/>&nbsp;There are no userslist.
					<? }?>
			<div align="center">
				<?php				
					echo $this->paginationControl(
					$this->vatTData,
					'sliding',
					array('partial/paginator.phtml', 'Application'),
					array(
						'route' => 'user',
						'id' =>$this->id
						)
					);
				?>
			</div>			
			</div>
		<div class="col-md-4">
			<?php include('right-side-bar.phtml');?>
		</div>
	</div>
	</div>
