<?php 
	 $ses_id=$_SESSION['user']['user_id'];
	 if(!isset($ses_id) && $ses_id == "")
	 {
?>
 <script>
	window.location = '<?php echo $baseUrl;?>/users/login'
 </script>
				<?php }?>
<div class="container min_height">
	<div class="row">
	
		<div class="col-md-9">
		<div class="panel panel-default">
				<div class="panel-body">
				<?php
				if(isset($this->allTests) && $this->allTests!=""){
				
					 $base_user_id = base64_encode($this->allTests->u_id);
					?>
				  <div class="col-md-3 well">
						<?php if(!isset($this->allTests->user_profile_photo)){?>
						<img alt="" src="<?php echo $basePath?>/images/<?php echo $this->allTests->user_photo;?>" style="width:140px;height:150px;">
						<?php } else{?>
						<img alt="" src="<?php echo $basePath?>/images/<?php echo $this->allTests->user_profile_photo;?>" style="width:140px;height:150px;">
						<?php }?>
				</div><span style="margin-left:414px;"><?php if(isset($ses_id) && $ses_id == $this->allTests->u_id){?><a href="<?php echo $baseUrl; ?>/edit-profile/<? echo $base_user_id;?>">edit Profile</a><?php }?></span>
					 <div class="col-md-9">
                    <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">First Name :</label>
                      <div class="col-sm-9">
                       <?php if($this->allTests->first_name != ""){echo $this->allTests->first_name;}else{ echo 'N/A';}?>
                      </div>
                    </div>
					<div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Email:</label>
                      <div class="col-sm-8">
                         <?php if($this->allTests->email != ""){echo $this->allTests->email;}else{ echo 'N/A';}?>
                      </div>
                    </div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" style="color:#828282">Phone Number:</label>
                      <div class="col-sm-4">
                       <?php if($this->allTests->contact_number != "" && $this->allTests->public_or_private == "public"){echo $links->contact_number;}elseif($this->allTests->public_or_private == "private"){ echo 'hide';}else{echo 'N/A';}?>
                      </div>
					  <div class="col-sm-4">
					
					</div>
				</div>
				<div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">City:</label>
                      <div class="col-sm-8">
                      <?php if($this->allTests->city != ""){echo $this->allTests->city;}else{ echo 'N/A';}?>
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Face Book Profile Link:</label>
                      <div class="col-sm-8">
                      <?php if($this->allTests->fb_profile_link != ""){echo $this->allTests->fb_profile_link;}else{ echo 'N/A';}?>
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Message:</label>
                      <div class="col-sm-8">
                      <?php if($this->allTests->message != ""){echo $this->allTests->message;}else{ echo 'N/A';}?>
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Skills:</label>
                      <div class="col-sm-8">
					 <?php if($this->allTests->skills != ""){echo $this->allTests->skills;}else{ echo 'N/A';}?>
                        
                      </div>
                 </div>
                 </div>
				 <div class="col-md-12">
				 <div class="form-group row">
                      <label class="col-sm-4 form-control-label"><strong>Pics Upload:</strong></label>
                      <div class="col-sm-12">
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
                      </div>
                 </div>
				<div class="form-group row">
                      <label class="col-sm-4 form-control-label"><strong>Video links:</strong></label>
                  <div class="col-sm-12"> 
							<?php 
							if(isset($this->allTests->video_links) && $this->allTests->video_links!=""){
								$videos_result=explode(",",$this->allTests->video_links);
								$link=explode("/", $videos_result);
								$url=$link['2'];
								foreach($videos_result as $video)
								{
									$video_id = substr($video, strpos($video, "=") + 1);			
									$urlName=explode(".", $url);					
									if(isset($urlName)){
										if((isset($urlName['1'])) && ($urlName['1']=='youtube')){
											$video_url=$urlName['1'];								
											$image=explode("=", $link['3']);
											 $image=$image['1'];
											$imageCode = strstr($image, ',', true);
											$imageUrl="http://i.ytimg.com/vi/".$imageCode."/default.jpg";
										}else if(isset($urlName['1']) && $urlName['1']=='dailymotion'){
											$video_url=$urlName['1'];
											$image=explode("_", $link['4']);
											$imageCode=$image['0'];
											$imageUrl="http://www.dailymotion.com/thumbnail/video/".$imageCode;
										}else if(isset($urlName['0']) && ($urlName['0']=='vimeo')){
											$video_url= $urlName['0'];
											$imageCode = $link['5'];
											$hash = unserialize(file_get_contents("http://vimeo.com/api/v2/video/$imageCode.php"));
											$imageUrl=$hash[0]['thumbnail_medium'];
										}else{
											$video_url= '';
											$imageUrl= '';
										}
									}
							     ?>	
									
									<a href="<?php echo $baseUrl; ?>/play-video?watch=HeMmavFtJ3c"><img  src="<?php echo $imageUrl;?>">
							<?php }  } else { ?>
								No videos
							<?php } ?>
									
					
              </div>
                </div>
				 
		</div>
				<?php } else{echo 'no results to show';}?>
		</div>
		</div>
		
		</div>
		<div class="col-md-3">
			<?php include('right-side-bar.phtml');?>				
		</div>
	</div>
</div>