<div class="container min_height">
	<div class="row">
	
		<div class="col-md-9">
		<div class="panel panel-default">
				<div class="panel-body">
				<?php 
				 $ses_id=$_SESSION['user']['user_id'];
				//echo $user_session->user_id;
				if(isset($this->allTests)){
				foreach($this->allTests as $links){
					//print_r($links);
					//echo $links->u_id;
					$base_user_id = base64_encode($links->u_id);
					?>
				  <div class="col-md-3 well">
						<?php if(!isset($links->user_profile_photo)){?>
						<img alt="" src="<?php echo $basePath?>/images/<?php echo $links->user_photo;?>" style="width:140px;height:150px;">
						<?php } else{?>
						<img alt="" src="<?php echo $basePath?>/images/<?php echo $links->user_profile_photo;?>" style="width:140px;height:150px;">
						<?php }?>
				</div><span style="margin-left:414px;"><?php if(isset($ses_id) && $ses_id == $links->u_id){?><a href="<?php echo $baseUrl; ?>/edit-profile/<? echo $base_user_id;?>">edit Profile</a><?php }?></span>
					 <div class="col-md-9">
                    <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">First Name :</label>
                      <div class="col-sm-9">
                       <?php if($links->first_name != ""){echo $links->first_name;}else{ echo 'N/A';}?>
                      </div>
                    </div>
					<div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Email:</label>
                      <div class="col-sm-8">
                         <?php if($links->email != ""){echo $links->email;}else{ echo 'N/A';}?>
                      </div>
                    </div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" style="color:#828282">Phone Number:</label>
                      <div class="col-sm-4">
                       <?php if($links->contact_number != ""){echo $links->contact_number;}else{ echo 'N/A';}?>
                      </div>
					  <div class="col-sm-4">
					
					</div>
				</div>
				<div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">City:</label>
                      <div class="col-sm-8">
                      <?php if($links->city != ""){echo $links->city;}else{ echo 'N/A';}?>
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Face Book Profile Link:</label>
                      <div class="col-sm-8">
                      <?php if($links->fb_profile_link != ""){echo $links->fb_profile_link;}else{ echo 'N/A';}?>
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Message:</label>
                      <div class="col-sm-8">
                      <?php if($links->message != ""){echo $links->message;}else{ echo 'N/A';}?>
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Skills:</label>
                      <div class="col-sm-8">
					 <?php if($links->skills != ""){echo $links->skills;}else{ echo 'N/A';}?>
                        
                      </div>
                 </div>
                 </div>
				 <div class="col-md-12">
				 <div class="form-group row">
                      <label class="col-sm-4 form-control-label"><strong>Pics Upload:</strong></label>
                      <div class="col-sm-12">
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
                      </div>
                 </div>
				<div class="form-group row">
                      <label class="col-sm-4 form-control-label"><strong>Video links:</strong></label>
                  <div class="col-sm-12">
				  				
					<a href="http://localhost/video-collections/trunk/play-video?watch=OTM="><img alt="Greeku Veerudu Telugu Full Movie | Nagarjuna Akkineni | Nayantara | S Thaman" src="http://i.ytimg.com/vi/4gmGRztRSGQ/default.jpg">
						</a>		
									
					<a href="http://localhost/video-collections/trunk/play-video?watch=MTI5"><img alt="MR. Productions &amp; Nine Productions 'Two Side Love'" src="http://i.ytimg.com/vi/scTWs5F5Mn4/default.jpg"></a>		
									
					<a href="http://localhost/video-collections/trunk/play-video?watch=MTk0"><img alt=" Hello Brother Trailer || Telugu Short Film Trailer/ Teaser || by Ajay Ejjada || Creative Frames" src="http://i.ytimg.com/vi/qjlRu_99Z1A/default.jpg">
						</a>	
					<a href="http://localhost/video-collections/trunk/play-video?watch=OTM="><img alt="Greeku Veerudu Telugu Full Movie | Nagarjuna Akkineni | Nayantara | S Thaman" src="http://i.ytimg.com/vi/4gmGRztRSGQ/default.jpg">
					</a>
					<a href="http://localhost/video-collections/trunk/play-video?watch=OTM="><img alt="Greeku Veerudu Telugu Full Movie | Nagarjuna Akkineni | Nayantara | S Thaman" src="http://i.ytimg.com/vi/4gmGRztRSGQ/default.jpg">
					</a>
              </div>
                </div>
				 
		</div>
				<?php } }else{echo 'no results to show';}?>
		</div>
		</div>
		
		</div>
		<div class="col-md-3">
			<?php include('right-side-bar.phtml');?>				
		</div>
	</div>
</div>