<div class="container  min_height">
	<form class="form-horizontal">
	  <div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">Video Title</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="video_title" name="video_title" placeholder="Video Title">
		</div>
	  </div>
	  <div class="form-group">
		<label for="inputPassword3" class="col-sm-2 control-label">Video Link</label>
		<div class="col-sm-10">
		  <textarea class="form-control" rows="3" id="video_link" name="video_link"></textarea>
		</div>
	  </div>
	  <div class="form-group">
		<label for="inputPassword3" class="col-sm-2 control-label">Video Description</label>
		<div class="col-sm-10">
		  <textarea class="form-control" rows="3" id="video_desc" name="video_desc"></textarea>
		</div>
	  </div>
	  <div class="form-group">
		<label for="inputPassword3" class="col-sm-2 control-label">Category</label>
		<div class="col-sm-10">
		  <select class="form-control" id="video_cat" name="video_cat">
			  <option >1</option>
			  <option>2</option>
			  <option>3</option>
			  <option>4</option>
			  <option>5</option>
		 </select>
		</div>
	  </div>
	 <div class="form-group">
		<label for="inputPassword3" class="col-sm-2 control-label">Video Image</label>
		 <div class="col-sm-10">
			<input type="file" name="video_img" id="video_img" class="file">
		 </div>
	 </div>
	  <div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
		  <div class="radio">
			<label>
			  <input type="radio" id="video_type" name="video_type" > Normal video
			</label>
			<label>
			  <input type="radio" id="video_type" name="video_type" > Featured video
			</label>
		  </div>
		</div>
	  </div>
	  <div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
		  <button type="submit" class="btn btn-default">Sign in</button>
		</div>
	  </div>
	</form>
</div>