 <?php if(isset($_SESSION['admin']['user_id'])){ 
 ?>
 <div class="container min_height">
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Add Category</h1>
      </div>
      <div class="modal-body">
          <form id="categoryForm" class="form col-md-12 center-block" method="POST">
            <div class="form-group">
              <input type="text" class="form-control" id="catname" name="catname"  value="<? if(isset($catData['category_name'])){ echo $catData['category_name'] ;}?>" placeholder="Category Name">
			  <span id="catnameError" style="color:red"></span>
            </div>
		<?php	if(isset($_GET['cid']) && $_GET['cid']!=''){ ?>
		<script>
			$(function(){
				$('#chk_id').prop("checked", true);
				$("#hidSpan").show();
				 $("#hidCheck").hide();
			});
		</script>
	<?php } ?> 
			<span id="hidCheck" style="display:none;">
				<div class="form-group">
					<label> Add a sub category also </label>&nbsp;&nbsp;<input type="checkbox" id="chk_id" name="chk_id" onclick="wantChked();">
				</div>
			</span>
			<input type="hidden" name="countbuttons" id="countbuttons" value="<? if(isset($subcatData) && $subcatData!=""){ echo count($subcatData);}else{?> 1 <?php } ?>" />
			<span id="hidSpan" style="display:none;">
				<?php if(count($this->subcatData)==0){?>
					<div class="form-group" id="companyText1">
						<label for="company-name1" class="control-label col-md-3 col-sm-3 col-xs-12">Subcategory</label>
							<div class="col-md-5 col-sm-6 col-xs-12 pos_r">
								<input type="text" class="form-control col-md-7 col-xs-12" name="cat_name[]" id="cat_name1" placeholder="Subcategory Name">
							</div>
							<button type="button" class="btn btn-success reset_btn" onClick="removeSubCat(1)">Remove Subcateogry</button>
					</div>
				<?php } else{ $k=1; foreach($this->subcatData as $key=>$subCat){ ?>
					<div class="form-group" id="companyText<?php echo $k;?>">
						<label for="company-name<?php echo $k;?>" class="control-label col-md-3 col-sm-3 col-xs-12">Subcategory</label>
							<div class="col-md-5 col-sm-6 col-xs-12 pos_r">
								<input type="text" class="form-control col-md-7 col-xs-12" name="cat_name[]" id="cat_name<?php echo $k;?>" value="<? echo $subCat;?>" placeholder="Subcategory Name">
							</div>
							<button type="button" class="btn btn-success reset_btn" onClick="removeSubCat('<?php echo $k;?>')">Remove Subcateogry</button>
					</div>
				<?php $k++; } } ?>
				<span id="add-companys"></span>
				<div class="form-group">
					<label for="company-name" class="control-label col-md-3 col-sm-3 col-xs-12">&nbsp;</label>
					<div class="col-md-5 col-sm-6 col-xs-12 pos_r">
						<button type="button" id="hidAdd" class="btn btn-primary  btn-bloconclick" onClick="addSubCat()">Add more subcategories</button>	
					</div>
				</div>
			</span>
            <div class="form-group text-center">
             <? if(isset($this->editcatdata[0]['category_id'])!=""){?>
				<button type="button" class="btn btn-primary  btn-bloconclick" onclick="addcategoryFunction(1);">Update</button>&nbsp;<button type="button" class="btn btn-primary  btn-bloconclick" onclick="backFunction(2);">Back</button>
			<?}else{ ?>
			<button type="button" class="btn btn-primary  btn-bloconclick" onclick="backFunction(2);">Back</button>&nbsp;&nbsp;<button type="button" class="btn btn-primary  btn-bloconclick" onclick="addCatCall();">Add</button>
			<?}?>
			<input type="hidden" value="<?php if(isset($catData['category_id']) && $catData['category_id']!=''){ echo $catData['category_id'];}else{}?>" id="cat_id" name="cat_id" ></p>
			<input type="hidden" value="" id="hid_cat_butt" name="hidbutton_value" >
			<input type="hidden" value="1" id="hid_cnt" name="hid_cnt">
            </div>
			<span id="errorMsg" style="color:red"></span>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>

    </div> <!-- /container -->
	
	<script>
	function addcategoryFunction(type){
	flag=true;
	var catname=$('#catname').val();
	var cattype=$('#cattype').val();
	var catbuttontype=$('#hid_cat_butt').val(type);
	if(catname==""){
		 $("#catnameError").html("Required");
		 flag=false;
	}else{
	  $("#catnameError").html("");
	}
	if(cattype==""){
		 $("#cattypeError").html("Required");
		 flag=false;
	}else{
	  $("#cattypeError").html("");
	}
	if(flag==true){
		$('#categoryForm').submit();
	}
	//window.location=BASE_URl+'/admin/add-category';
	}
	</script>
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>