<?php if(isset($_SESSION['admin']['user_id'])){
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath']; 
?>
<div class="container min_height" style="background:none;border:none;">
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="alert alert-dismissible alert-success" style="display:none" id="sucessdiv">
		<strong id="sucessMsg"></strong>
	</div>
  <div class="alert alert-dismissible alert-danger" style="display:none" id="errordiv">
		<strong id="errorMsg"></strong>
	</div>	
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Change Password</h1>
      </div>
      <div class="modal-body">
          <form id="changePasswordForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="password" class="form-control" id="oldPassword" name="oldPassword" placeholder="Old Password">
			  <span id="oldPwdError" style="color:red"></span>
            </div>
			<div class="form-group">
              <input type="password" class="form-control" id="newPassword" name="newPassword" placeholder="New Password">
			  <span id="newPwdError" style="color:red"></span>
            </div><div class="form-group">
              <input type="password" class="form-control"  id="confirmPassword" name="confirmPassword" placeholder="Confirm Password">
			  <span id="confirmPwdError" style="color:red"></span>
            </div>
            <div class="form-group">
              <button type="button" id="submit" class="btn btn-primary" onclick="changePassword('admin');">Save</button>
              <a href="<? echo $baseUrl.'/admin/users-list'?>"><button type="button" id="submit" class="btn btn-primary">Cancel</button></a>
			  <center><span id="reload"></span></center>
            </div>
          </form>
		  <input type="hidden" id="hidUserId" name="hidUserId" value="<?php echo $_SESSION['admin']['user_id'];?>">
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>
</div>
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>
<script>
$('#confirmPassword').keypress(function(e){
	if( e.keyCode == 13 ){
		changePassword('admin');
	}
});
</script>
