 <?php if(isset($_SESSION['admin']['user_id'])){
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath']; 
 ?>
<div class="container mar_t min_height">
	<div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
          <h1 class="text-center">Dashboard</h1>
      </div>
	   <div class="modal-body">
		  <div>
			  <center>
				<p><a class="btn btn-primary  btn-block" href="<?php echo $baseUrl; ?>/admin/categories-list">Category</a></p>
				<p><a class="btn btn-primary  btn-block" href="javascript:void(0)" onclick="CategoryFunction(1)" >Issues</a></p>
			  </center>
		  </div>
	  </div>
     <div class="clearfix"></div>
  </div>
  </div>
</div>

    </div> <!-- /container -->
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>