<div class="container reg_w_12 min_height">
	<div class="panel-default mar_t">
		<div class="panel-heading reg_bg">
			<h3 class="panel-title">Welcome To Admin</h3>
		</div>  		
		<form  id="frm_meth" name="frm_meth" method="post" action="">		
			<div class="panel-body" id="tab_1_hide">
				<div class="form-horizontal">				
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-3 control-label">Admin Email</label>
						<div class="col-sm-8">
							<input type="email" class="form-control" id="user_email" placeholder="Email" name="user_email" value="">
							<span id="emailError" style="color:red"></span>
						</div>
					</div>
					<span id="errorMsg" style="color:red"></span>
					<div class="form-group">
						<label for="inputPassword3" class="col-sm-3 control-label">Password</label>
						<div class="col-sm-8">
							<input type="password" class="form-control" id="user_password" name="user_password" value="" placeholder="Password">
							<span id="passwordError" style="color:red"></span>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-8 col-lg-offset-3">
							<button type="button" class="btn btn-primary " onClick="adloginValidations();">Continue</button>
						</div>
					</div>
				</div>
			</div>
		</form>			
	</div>	
</div>
