<div class="container min_height reports_page">
		<table>
			<tr>
				<td><h3 class="color_link">Links posted today</h3></td>
				<td><h3 class="color_link"><?echo $this->todayVideoCount;?></h3></td>
			</tr>
			<tr>
				<td><h3 class="color_link_posted">Users signed up today</h3></td>
				<td><h3 class="color_link_posted"><?echo $this->todayUsersCount;?></h3></td>
			</tr>
			<tr>
				<td>
					<h3 class="color_link_totle">Total Videos in present</h3></td>
					<td><h3 class="color_link_totle"><?echo $this->presentVideoCount;?></h3></td>
				</tr>
			<tr>
				<td>&nbsp;</td><td><a href="/admin/index?type=customer">BACK</a></td>
			</tr>
		</table>
</div>