<?php if(isset($_SESSION['admin']['user_id'])){
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath']; 
?>
<div class="container mar_t mar_b min_height" style="position:relative">
<head>
  <link rel="stylesheet" type="text/css" href="">
  <link href="<?php echo $basePath; ?>/css/jquery.datatable.css" rel="stylesheet">
  <script src="<?php echo $basePath;?>/js/jquery.datatable.min.js"></script>
</head>
  <table id="example" class="table table-bordered table-hover">
	<div style="position:absolute;top:3px;left:200px;z-index:300">

 </div>
    <thead>
      <tr><th>#</th>
     <th>User Name</th>
	 <th>Email</th>
	 <th>Phone&nbsp;Number</th>
	 <th>User Status</th>
	 <th>Gallery</th>
     <th>Action</th>
     </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  </div>
  <center><span id="reload"></span></center>
  <script>
  $(function(){
  $('#reload').html('<img src=<?php echo $basePath; ?>/images/ajax-loader.gif />');
  $.ajax({
        type:    'GET',
        dataType:'json',
        url: BASE_PATH+'/admin/userinfo-ajax',
        success: function(data){
		$('#reload').html('');
            eval(data);
            var oTable = $('#example').dataTable( {
                aoColumnDefs: [{bSortable: false,
                                aTargets: [ 0 ]
                                }],
                "bStateSave": true,
                "sRowSelect": "multi",
                "sPaginationType": "full_numbers",
				 "bAutoWidth": false,
                "bProcessing": true,
                "aaData": data,
                "aoColumns": [
                    { "mData": "user_id",'sWidth': '5%'},
                    { "mData": "user_name",'sWidth': '15%' },
                    { "mData": "email_id",'sWidth': '17%'},
                    { "mData": "contact_number",'sWidth': '15%'},                   
                    { "mData": "status",'sWidth': '15%'},
					 { "mData": "pics_videos",'sWidth': '15%'},
                    { "mData": "action",'sWidth': '18%'}                        
                ],
            });    
        }
    });
});
  </script>
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>