<?php if(isset($_SESSION['admin']['user_id'])){
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath']; 
?>
<div class="container mar_t mar_b min_height" style="position:relative">
<head>
  <link rel="stylesheet" type="text/css" href="">
  <link href="<?php echo $basePath; ?>/css/jquery.datatable.css" rel="stylesheet">
  <script src="<?php echo $basePath;?>/js/jquery.datatable.min.js"></script>
</head>
	<div class="form-controller" style="float:left">	
		<?php if(isset($this->countVideos) && $this->countVideos!=0) { ?>
		<input type="button" class="btn" id="actId" name="actId" value="Activate" onClick="activeAll('a')" />
		<input type="button" class="btn" id="deactId" name="deactId" value="Deactive" onClick="activeAll('d')" /> 
		<?php } ?>        
	</div><br/>
  <table id="example_div" class="table table-bordered table-hover">
	<div style="position:absolute;top:3px;left:200px;z-index:300">
		
 </div>
    <thead>
      <tr>
	  <th><input type="checkbox" name="selcheck" id="selcheck[]" onChange="checkAll(this)">&nbsp;&nbsp;Select All</th>
	  <th>Email</th>
	  <th>Phone</th>
	  <th>Link</th>	 
	  <th>Status</th>	 
     </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  </div>
  <center><span id="reload"></span></center>
  <script>
  $(function(){
  $('#reload').html('<img src=<?php echo $basePath; ?>/images/ajax-loader.gif />');
  $.ajax({
        type:    'GET',
        dataType:'json',
        url: BASE_PATH+'/admin/user-video-ajax?uid=<?php echo $_GET['uid'];?>',
        success: function(data){
		$('#reload').html('');
            eval(data);
            var oTable = $('#example_div').dataTable( {
                aoColumnDefs: [{bSortable: false,
                                aTargets: [ 0 ]
                                }],
                "bStateSave": true,
                "sRowSelect": "multi",
                "sPaginationType": "full_numbers",
				 "bAutoWidth": false,
                "bProcessing": true,
                "aaData": data,
                "aoColumns": [
                    { "mData": "action",'sWidth': '20%'},              
                    { "mData": "email",'sWidth': '20%'},              
                    { "mData": "phone",'sWidth': '20%'},              
                    { "mData": "link",'sWidth': '55%'},
                    { "mData": "status",'sWidth': '25%'},
                 
                ],
            });    
        }
    });
});
function activeAll(roleMode){
	var num=""; var count=0;
	var deleteId=document.getElementsByTagName("input");
	for(var i = 0; i < deleteId.length; i++){
		if(deleteId[i].name=="check[]"){
			if(deleteId[i].checked){
				num+=deleteId[i].value+',';
				count++;
			}
		}
	}
	if(count==0){
		alert("Please check only one field!");
		return false;
	}else{
		if(confirm("Are you sure you want change status row?")){
			$.ajax({
				type	: 	"POST",
				cache	:	false,
				url		:  BASE_URL+'/admin/status-mode',
				data	:  {ids:num,type:'videolinks',roleMode:roleMode},
				success	: 	function(res) {
					if(res.status == 1){
						 window.location=BASE_URL+"/admin/user-videos?uid=<?php echo $_GET['uid'];?>";	
					}
				}
			});						
		}
	}
}	
function selectAll(){
	var checkval=document.getElementsByName('check[]');	
	var len; var count=0;
	len=checkval.length;
	for(var i = 0;i < len; i++){
		 if(checkval[i].checked){
		 count++;
		}
	}
	if(checkval.length==count){
		document.getElementById('selcheck[]').checked=true;
	}else{
		document.getElementById('selcheck[]').checked=false;
	}
}
function checkAll(ele){
	var checkboxes = document.getElementsByTagName('input');
     if (ele.checked) {
         for (var i = 0; i < checkboxes.length; i++) {
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = true;
             }
         }
     } else {
         for (var i = 0; i < checkboxes.length; i++) {
             if (checkboxes[i].type == 'checkbox') {
                 checkboxes[i].checked = false;
             }
         }
     }
}
  </script>
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>