<?php if(isset($_SESSION['admin']['user_id'])){
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath']; 
?>
<div class="container mar_t mar_b min_height" style="position:relative">
<head>
  <link rel="stylesheet" type="text/css" href="">
  <link href="<?php echo $basePath; ?>/css/jquery.datatable.css" rel="stylesheet">
  <script src="<?php echo $basePath;?>/js/jquery.datatable.min.js"></script>
</head>
  <table id="example" class="table table-bordered table-hover">
	<div style="position:absolute;top:3px;left:200px;z-index:300">
	<button type="button" class="btn btn-primary  btn-bloconclick btn-sm" id="back" name="back"  onclick="backFunction(0);">Back</button>&nbsp;&nbsp;

 </div>
    <thead>
      <tr><th>#</th>
     <th>User Name</th>
	 <th>Email</th>
	 <th>Phone Number</th>
	 <th>Status</th>
     <th>Action</th>
     </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  </div>
  <center><span id="reload"></span></center>
  <script>
  $(function(){
  $('#reload').html('<img src=<?php echo $basePath; ?>/images/ajax-loader.gif />');
  $.ajax({
        type:    'GET',
        dataType:'json',
        url: BASE_PATH+'/admin/userinfo-ajax',
        success: function(data){
		$('#reload').html('');
            eval(data);
            var oTable = $('#example').dataTable( {
                aoColumnDefs: [{bSortable: false,
                                aTargets: [ 0 ]
                                }],
                "bStateSave": true,
                "bAutoWidth": true,
                "sRowSelect": "multi",
                "sPaginationType": "full_numbers",
                "bProcessing": true,
                "aaData": data,
                "aoColumns": [
                    { "mData": "user_id" },
                    { "mData": "user_name" },
                    { "mData": "email_id", "sWidth": "100px"},
                    { "mData": "contact_number"},
                    { "mData": "status"},
                    { "mData": "action"}                        
                ] 
            });    
        }
    });
});
  </script>
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>