<?php if(isset($_SESSION['admin']['user_id'])){
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath']; 
?>
<div class="container mar_t mar_b min_height" style="position:relative">
<head>
  <link rel="stylesheet" type="text/css" href="">
  <link href="<?php echo $basePath; ?>/css/jquery.datatable.css" rel="stylesheet">
  <script src="<?php echo $basePath;?>/js/jquery.datatable.min.js"></script>
</head>
  <table id="example_div" class="table table-bordered table-hover">
	<div style="position:absolute;top:3px;left:200px;z-index:300">

 </div>
    <thead>
      <tr>
	  <th><input type="checkbox" name="selcheck" id="selcheck[]" onClick="checkAll()">&nbsp;&nbsp;Select All</th>
	  <th>Thumb Pic</th>	 
	  <th>Status</th>	 
     </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  </div>
  <center><span id="reload"></span></center>
  <script>
  $(function(){
  $('#reload').html('<img src=<?php echo $basePath; ?>/images/ajax-loader.gif />');
  alert();
  $.ajax({
        type:    'GET',
        dataType:'json',
        url: BASE_PATH+'/admin/user-pics-ajax?uid=<?php echo $_GET['uid'];?>',
        success: function(data){
		$('#reload').html('');
            eval(data);
            var oTable = $('#example_div').dataTable( {
                aoColumnDefs: [{bSortable: false,
                                aTargets: [ 0 ]
                                }],
                "bStateSave": true,
                "sRowSelect": "multi",
                "sPaginationType": "full_numbers",
				 "bAutoWidth": false,
                "bProcessing": true,
                "aaData": data,
                "aoColumns": [
                    { "mData": "action",'sWidth': '5%'},              
                    { "mData": "thumb_image",'sWidth': '25%'},
                    { "mData": "status",'sWidth': '10%'}                 
                ],
            });    
        }
    });
});




function delstudent(){
	var num=""; var count=0;
	var deleteId=document.getElementsByTagName("input");
	for(var i = 0; i < deleteId.length; i++){
		if(deleteId[i].name=="check[]"){
			if(deleteId[i].checked){
				num+=deleteId[i].value+',';
				count++;
			}
		}
	}
	if(count==0){
		alert("Please Check Only One Field!");
		return false;
	}else{
		if(confirm("Are you sure you want delete row?")){
		 window.location="listofquestion.php?qdelid="+num;					
		}
	}
}	
function selectAll(){
	var checkval=document.getElementsByName('check[]');	
	var len; var count=0;
	len=checkval.length;
	for(var i = 0;i < len; i++){
		 if(checkval[i].checked){
		 count++;
		}
	}
	if(checkval.length==count){
		document.getElementById('selcheck[]').checked=true;
	}else{
		document.getElementById('selcheck[]').checked=false;
	}
}
function checkAll(){
	if(document.getElementById('selcheck[]').checked){
		$("INPUT[type='checkbox']").attr('checked',true);
	}else{
		$("INPUT[type='checkbox']").attr('checked',false); 
	}
}
  </script>
<?php }else{?>
  <script>window.location=BASE_URL+"/admin";</script>
<?}?>