<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];	
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
	<head>  
	  <title>VideoBlogger</title>
		<script> 	
			var BASE_URL = '<?php echo $baseUrl;?>';
			var BASE_PATH = '<?php echo $basePath;?>';	
		</script>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="shortcut icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">
		<link rel="icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">	
		<!-- CSS Start -->	
		<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
		<link href="<?php echo $basePath; ?>/css/main.css" rel="stylesheet">
		<link href="<?php echo $basePath; ?>/css/custom.css" rel="stylesheet">
		<link href="<?php echo $basePath; ?>/css/sticky-footer-navbar.css" rel="stylesheet">
		<!-- Js Script-->	
		<script src="<?php echo $basePath; ?>/js/jquery-112min.js"></script>
		<script src="<?php echo $basePath; ?>/js/bootstrap.min.js"></script>
		<script src="<?php echo $basePath; ?>/js/isotope.pkgd.min.js"></script>
		<script src="<?php echo $basePath; ?>/js/poorapo.isotope.js"></script>
		<script src="<?php echo $basePath; ?>/js/commonfunctions.js"></script>
		<script src="<?php echo $basePath; ?>/js/jquery.bootstrap.newsbox.min.js"></script>
	</head>
	<body>
		<nav class="navbar-default-custom-c navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $baseUrl . '/admin/dashboard-menu'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Poorapo"/></h1></a>
				</div>
				<?php if(isset($_SESSION['admin']['user_id']) && $_SESSION['admin']['user_id']!=''){ ?>
					<div id="navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav">	
								<li><?php echo $_SESSION['admin']['user_name']; ?></li>
								<li><a href="<?php echo $baseUrl; ?>/admin/dashboard-menu">Admin</a></li>
								<li><a href="<?php echo $baseUrl; ?>/admin/logout">log Out</a></li>
							</ul>
					</div>
				<? } ?>
		</nav>