<footer class="footer">
   	<div class="copy_right"> 
	<div class="container"> 
	<div class="row">
		<div class="col-md-7 footer_linksa">
			<p>
				<a href="#"> Home </a>
				<a href="#"> About </a>
				<a href="#"> Privacy Policy</a>
				<a href="#"> Terms of Service </a>
				<a href="#"> Contact Us</a>
			</p>
		</div> 
		<div class="col-md-5">
		<p class="copy_right_t">Designed and Developed by <a href="http://aapthitech.com" target="_blank">Aapthi Technologies</a></p>
	</div>
	</div> 
	</div> 
	</div>	
    </footer> 
  </body>
</html>
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-531e904b28537972" async="async"></script>
<script type="text/javascript">
    $(function () {
        $(".latestvideos").bootstrapNews({
            newsPerPage: 9,
            autoplay: true,
			pauseOnHover:true,
            direction: 'up',
            newsTickerInterval: 4000,
            onToDo: function () {
                //console.log(this);
            }
        });
	});
</script>