<?php
	if(isset($_SERVER['REDIRECT_URL']) && $_SERVER['REDIRECT_URL']!=""){		
		$page=basename($_SERVER['REDIRECT_URL']);
		if($page=='all-profiles'){
			 $parmsName  = "profile";	
		}else if($page=='profile-user'){
			 $parmsName  = "profile";	
		}else if($page=='edit-profile'){
			 $parmsName  = "profile";	
		}else{
			$parmsName  = "all";			
		}
	}else{
		$parmsName  = "all";			
	}
	$header=$this->action('Application\Controller\IndexController', 'headerAction',$parmsName);	
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
	$catData = $header->headerarray['catData'];	
	$videoData = $header->headerarray['videoData'];
	$topVideos = $header->headerarray['topVideos'];	
	$allCities = $header->headerarray['allCities'];	
	if($_SERVER['REQUEST_URI']=='/'){
		$_SESSION['tilte_top'] = 'sfadda.com';
		$image_name = $basePath.'/img/logo.png';
		$_SESSION['tilte_imag'] = $image_name;
	}else if($_SERVER['REQUEST_URI']=='/video-collections/trunk/'){
		$_SESSION['tilte_top'] = 'sfadda.com';
		$image_name = $basePath.'/img/logo.png';
		$_SESSION['tilte_imag'] = $image_name;
	}else{
		if(isset($_SESSION['tilte_top']) && $_SESSION['tilte_top']!=""){
			$_SESSION['tilte_top'] = $_SESSION['tilte_top'];
		}else if(isset($_SESSION['tilte_imag']) && $_SESSION['tilte_imag']!=""){
			$_SESSION['tilte_imag'] = $_SESSION['tilte_imag'];
		}
	}
	if($_SERVER['HTTP_HOST']=='sfadda.com'){$appid='685804858155190';}else {$appid='685804858155190';}
?>

<!DOCTYPE html>
<html lang="en">
  <head>  
  <title><?php if(isset($_SESSION['tilte_top'])){ echo $_SESSION['tilte_top']; }else{?>sfadda.com<?php } ?></title>
	<script> 	
		var BASE_URL = '<?php echo $baseUrl;?>';
		var BASE_PATH = '<?php echo $basePath;?>';	
	</script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property="og:title" content="<?php if(isset($_SESSION['tilte_top'])){ echo $_SESSION['tilte_top']; }else{?>sfadda.com<?php } ?>" />
	<meta property="og:type" content="Website" />
	<meta property="og:image" content="<?php if(isset($_SESSION['tilte_imag'])){ echo $_SESSION['tilte_imag']; } ?>" />
	<meta property="og:url" content="<?php if(isset($_SESSION['tilte_top'])){ echo $_SESSION['tilte_top']; }else{?>sfadda.com<?php } ?>" />
	<meta property="fb:app_id" content="<? echo $appid;?>">
	<meta property="og:description" content="<?php if(isset($_SESSION['tilte_top'])){ echo $_SESSION['tilte_top']; }else{?>sfadda.com<?php } ?>" />
	<meta property="og:site_name" content="<?php echo $baseUrl; ?>" />
    <link rel="shortcut icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">	
	<!-- CSS Start -->	
	<link href='//fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href="<?php echo $basePath; ?>/css/main.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/custom.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/sticky-footer-navbar.css" rel="stylesheet">
	<!--<link href="<?php echo $basePath; ?>/css/magnafic.css" rel="stylesheet" />
	<link href="<?php echo $basePath; ?>/css/magnaficpopup.css" rel="stylesheet" />-->
	<!-- Js Script-->	
	<script src="<?php echo $basePath; ?>/js/jquery-112min.js"></script>
	<script src="<?php echo $basePath; ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/isotope.pkgd.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/poorapo.isotope.js"></script>
    <script src="<?php echo $basePath; ?>/js/commonfunctions.js"></script>
	<!--<script src="<?php echo $basePath; ?>/js/popup.min.js"></script>-->
	
    <script src="<?php echo $basePath; ?>/js/jquery.bootstrap.newsbox.min.js"></script>
	<link href="<?php echo $basePath; ?>/dist/lsb.css" rel="stylesheet">
	<script src="//code.jquery.com/jquery.min.js"></script>
	<script src="<?php echo $basePath; ?>/dist/lsb.min.js"></script>
	<link rel="stylesheet" href="<?php echo $basePath; ?>../src/lsb.css">
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="<?php echo $basePath; ?>../src/lsb.js"></script>
  </head>
  <body>
  <!-- Top bar -->
  <div class="top_bar">
	  <div class="container">
		  <div class="row">
			  <div class="col-md-6 smhide">
			<?php
			$date_array = getdate();
			?>
			Today: <?php echo $date_array['weekday'];?>, <?php echo $date_array['month'];?> <?php echo $date_array['mday'];?>, <?php echo $date_array['year'];?> Last Update: <?php echo $date_array['hours'];?>:<?php echo $date_array['minutes'];?>
			</div>
			  <div class="col-md-6 topmenu_links my_ac_drop_down">
					<? if(isset($_SESSION['user']['user_id']) && $_SESSION['user']['user_id']!=""){ $userid= base64_encode($_SESSION['user']['user_id']);
					$usersid= base64_decode($userid);?>
					<div class="btn-group " role="group">							
							<i>Welcome</i> &nbsp;&nbsp;<span class="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor: pointer; cursor: hand;" id="top_bar_drop_down">
							 <? if(strlen($_SESSION['user']['displayName'])>8){echo substr(ucfirst($_SESSION['user']['displayName']),0,8) . '...'; }else{echo ucfirst($_SESSION['user']['displayName']);} ?> 
								<span class="caret" style="cursor: pointer; cursor: hand;"></span>
							</span>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $baseUrl; ?>/users/videos-list">My Uploads</a><li>
							<li><a href="<?php echo $baseUrl; ?>/profile-user?uid=<? echo base64_encode($usersid."-143"); ?>">Profile</a><li>
							<li><a href="<?php echo $baseUrl; ?>/users/change-password">Change Password</a></li>
							<li><a onClick="outLoggedFine();" href="javascript:void(0);" >Sign Out</a></li>
						</ul>
					</div>
					<? } else{?>
					<ul class="list-inline">						
						<li><a href="<?php echo $baseUrl; ?>/users/login">Sign In</a><li>
						<li>|<li>
						<li><a href="<?php echo $baseUrl; ?>/users/register">Sign Up</a></li>
					</ul>
					<? } ?>
			  </div>
		  </div>
	  </div>
  </div>
    <!-- Fixed navbar -->
    <nav class="navbar-default-custom-c navbar navbar-default navbar-fixed-top">
		<div class="container" style="position:relative">
			<div class="ad_pos_ab">
			<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- topbanner -->
					<ins class="adsbygoogle"
						 style="display:inline-block;width:728px;height:90px"
						 data-ad-client="ca-pub-9408213208791031"
						 data-ad-slot="4974503839"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script></div>
			<div class="navbar-header">         
				<a class="navbar-brand" href="<?php echo $baseUrl . '/'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="sfadda.com" width="90%"/></h1></a>
			</div>
		</div>
    </nav>
<div class="container">
<div class="row">
<div class="col-md-2 filter_cate2 ">
<h4 style="font-family: Roboto"><a class="hover_body"href="<?php echo $baseUrl;?>/all-profiles?cat=all" >Cast & Crew</a></h4> 
</div>
<div class="col-md-10">
<div class="latest_news alert mar_bnone">
	<div class="pos_relative" id="scroll">
	<div class="close_lnews"><button type="button" class="close" data-dismiss="alert">×</button></div>
		<span>
		<marquee behavior="scroll"  direction="left"  scrollamount="4" onmouseover="javascript:this.setAttribute('scrollamount','0');" onmouseout="javascript:this.setAttribute('scrollamount','5');">
		<ul class="list-inline">
			<?  foreach($topVideos as $key=>$videolinks){
					// if($key == 25){ break; }
				$video_id = base64_encode($videolinks->v_id);
			?>
				<li><a href="<?php echo $baseUrl; ?>/play-video?watch=<? echo $video_id;?>"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> <? echo $videolinks->v_title;?></a></li>	
			<? } ?>				
		</ul>
		</marquee>
		</span>
	</div>
</div>
</div>
</div>
</div>
<div class="search_bar">
	<div class="container">
	<div class="row">
		<div class="col-md-5 filter_cate">
			<a href="<?php echo $baseUrl . '/'; ?>" class="smhide"><button type="button" class="home_icon"><span class="glyphicon glyphicon-home" style="color:#2fa4e7"></span></button></a>
			&nbsp;&nbsp;
			<div class="btn-group " role="group">
				<?php if($parmsName =="profile") {?>
				<!-- Skills Label -->
				<span style="font-family: Roboto;font-size:16px">SKILLS</span> &nbsp;&nbsp;&nbsp;
				<!-- END -->
				<?php } else {?>
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				CATEGORIES &nbsp;&nbsp;&nbsp;
				<img  src="<?php echo $basePath; ?>/img/menu.png" alt="ads">
					<span class="caret"></span>
				</button>
				<?php } ?>
					
				<?php if($parmsName =="profile") {?>
				<!-- Skills Drop Down -->
					<select style="height:30px;padding-right: 65px;" id="u_c_id" value="u_c_id" onChange="filterByskill();">
								<option value="">Select</option>
					<?php if(isset($catData)){ foreach($catData as $catinfo){ ?>
								<option value="<?php echo $catinfo->u_c_id; ?>"><?php echo ucfirst($catinfo->u_category_name); ?></option>
								<?php } } ?>
					</select>	
				<!--End-->							
					<?php  } else {?>
				<ul class="dropdown-menu" <?php if($parmsName =="profile") { ?>style=" height:350px; overflow:auto; left:0 !important"<?php } else{?> style="left:0 !important" <?php } ?> >
					<? 
					if(isset($catData)){ foreach($catData as $key=>$catinfo){
							foreach($catinfo as $catid=>$catname){
								if(count( $catinfo )>1){
									$dropMenu = 'dropdown-submenu';
								}else{
									$dropMenu = '';
								}
								if($key == $catid){ ?>
									<li class ="<? echo $dropMenu; ?>" tabindex='-1'>
									<?php if($parmsName =="profile") {?>
									<a href="<?php echo $baseUrl; ?>/all-profiles?cat=<? echo $catid;?>"><? echo $catname;?></a>
									<?php } else {?>
									<a href="<?php echo $baseUrl; ?>/cat/<? echo $catid;?>"><? echo $catname;?></a>
									<?php } ?>	
										<ul class='dropdown-menu' role = 'menu'>
											<? foreach($catinfo as $catid=>$catname){ 
													if($key != $catid){	?>
														<?php if($parmsName =="profile") {?>
															<li><a tabindex='-1' href="<?php echo $baseUrl; ?>/all-profiles/<? echo $catid;?>"><? echo $catname;?></a></li>
														<?php } else{?>
														<li><a tabindex='-1' href="<?php echo $baseUrl; ?>/cat/<? echo $catid;?>"><? echo $catname;?></a></li>
													<?php } ?>
											<? } } ?> 			
										</ul>										
									</li>
					<?php } } } }	
					?>
				</ul>
				<?php } ?>
			</div></div>
			<?php if($parmsName =="profile") {?>
			<!-- Cities DropDown -->
			<div class="col-md-3">
				<label>CITY</label>&nbsp;&nbsp;
				<select style="height:30px;width:auto;padding-right: 85px;" id="c_id" value="c_id" onChange="filterByCity();">
					<option value="">Select</option>
					<?php if(isset($allCities) && count($allCities)>0) { 
						foreach($allCities as $allCity){
					?>
					<option value="<?php echo $allCity->c_id; ?>"><?php echo ucfirst($allCity->c_name); ?></option>
					<?php } } ?>
				</select>
			</div>
			<!-- End -->
			<?php } ?>
		
			<?php if($parmsName =="profile") {?>
			<!-- Search Text BOX-->
				<div class="col-md-4 input_search">
					<div class="input-group">
						<input id="nameSearch" placeholder="Search for name" class="form-control" type="textbox">
						<span class="input-group-btn">
						<button class="btn btn-default"  onClick="searchByName();" type="button" id="addressSearch">Search</button>
						</span>
					</div>
				</div>
			<!--End-->
			<?php } else { ?>
				<div class="col-md-7 input_search">
					<div class="input-group">
						<input id="videosSearch" placeholder="Search for videos" class="form-control" type="textbox">
						<span class="input-group-btn">
						<button class="btn btn-default" onKeypress="serachTitle();" onClick="searchByLocation();" type="button" id="addressSearch">Search</button>
						</span>
					</div>
				</div>
			<?php } ?>			
	</div>
	</div>
</div>
<style>
	html .ui-autocomplete {
		height: 300px;
	}	
</style>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript" charset="utf-8">
 FB.init({
  appId  : '<?php echo $appid ?>',
  status : true, 
  cookie : true, 
  xfbml  : true  
});
</script>
<link rel="stylesheet" href="<?php echo $basePath; ?>/css/jquery-ui-1-11-4.css">
<script src="<?php echo $basePath; ?>/js/jquery-ui-1-11-4.js"></script>
<script src="<?php echo $basePath; ?>/js/autocomplete.js"></script>
<?php
if(strpos($_SERVER['REQUEST_URI'],'register')!==false || strpos($_SERVER['REQUEST_URI'],'login')!==false){?>
	<script>
	$(window).scroll(function() {
		if ($(this).scrollTop() > 150) {
			$('.search_bar').addClass('');
		} else {
			$('.search_bar').removeClass('');
		}
	});
	</script>
<?} else { ?>
<script>
	$(window).scroll(function() {
		if ($(this).scrollTop() > 150) {
			$('.search_bar').addClass('search_bar_fix_top');
		} else {
			$('.search_bar').removeClass('search_bar_fix_top');			
		}
	});
</script>
<?php } ?>
<script>
$('#videosSearch').keypress(function(e){
	serachTitle(e);
	$(".ui-autocomplete").niceScroll({touchbehavior:false, cursorborder:"",cursorcolor:"#666",cursoropacitymax:0.6,cursorwidth:5,autohidemode: false,horizrailenabled:false});
	if( e.keyCode == 13 ){
		searchByLocation();
	}
});

function outLoggedFine(){	
	FB.logout(function(response){});
	  $.ajax({
		url: BASE_URL+'/users/logout',
		success: function(data){			
			if(data.output=='success'){
				window.location=BASE_URL;
			}
		}
	});
}
function filterByskill(){
	var catid= $("#u_c_id").val();
	var c_id = $("#c_id").val();
	if(c_id==""){
		window.location=BASE_URL+"/all-profiles?cat="+catid;
	}else{
		window.location=BASE_URL+"/all-profiles?cat="+catid+"&city="+c_id;
	}
}
function filterByCity(){
	var cat_id = $("#u_c_id").val();
	if(cat_id !=""){		
		cat_id = cat_id;
	}else{
		cat_id = "all";
	}
	var c_id = $("#c_id").val();
	if(c_id==""){
		window.location=BASE_URL+"/all-profiles?cat="+cat_id;
	}else{
		window.location=BASE_URL+"/all-profiles?cat="+cat_id+"&city="+c_id;
	}
	$("#c_id").val(c_id);
}
function searchByName(){
	var cat_id = $("#u_c_id").val();
	if(cat_id !=""){		
		cat_id = cat_id;
	}else{
		cat_id = "all";
	}
	var c_id = '<?php if(isset($_GET['city']) && $_GET['city']!=""){ echo $_GET['city']; }else{ echo ""; }  ?>';
	var nameSearch = $("#nameSearch").val();
	if(nameSearch==""){
		if(c_id==""){
			window.location=BASE_URL+"/all-profiles?cat="+cat_id;
		}else{
			window.location=BASE_URL+"/all-profiles?cat="+cat_id+"&city="+c_id;
		}
	}else{		
		if(c_id==""){
			window.location=BASE_URL+"/all-profiles?cat="+cat_id+"&u_name="+nameSearch;
		}else{
			window.location=BASE_URL+"/all-profiles?cat="+cat_id+"&city="+c_id+"&u_name="+nameSearch;
		}	
	}
}

$(document).ready(function() {
	var cat_id = "<?php if(isset($_GET['cat']) && $_GET['cat']!=""){ echo $_GET['cat']; }else{ echo "all"; } ?>";
	var c_id = '<?php if(isset($_GET['city']) && $_GET['city']!=""){ echo $_GET['city']; }else{ echo ""; }  ?>';
	$("#c_id").val(c_id);
	if(cat_id!="all"){
		$("#u_c_id").val(cat_id);
	}else{
		$("#u_c_id").val('');		
	}
	
});
</script>