<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
	$catData = $header->headerarray['catData'];	
	$videoData = $header->headerarray['videoData'];
	$topVideos = $header->headerarray['topVideos'];	
?>
<!DOCTYPE html>
<html lang="en">
  <head>  
  <title>VideoBlogger</title>
	<script> 	
		var BASE_URL = '<?php echo $baseUrl;?>';
		var BASE_PATH = '<?php echo $basePath;?>';	
	</script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">	
	<!-- CSS Start -->	
	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href="<?php echo $basePath; ?>/css/main.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/custom.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/sticky-footer-navbar.css" rel="stylesheet">
	<!-- Js Script-->	
	<script src="<?php echo $basePath; ?>/js/jquery-112min.js"></script>
    <script src="<?php echo $basePath; ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/isotope.pkgd.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/poorapo.isotope.js"></script>
    <script src="<?php echo $basePath; ?>/js/commonfunctions.js"></script>
    <script src="<?php echo $basePath; ?>/js/jquery.bootstrap.newsbox.min.js"></script>
  </head>
  <body>
  <!-- Top bar -->
  <div class="top_bar">
	  <div class="container">
		  <div class="row">
			  <div class="col-md-6">
			<?php
			$date_array = getdate();

			foreach ( $date_array as $key => $val )
			{ }
			?>
			Today: <?php echo $date_array['weekday'];?>, <?php echo $date_array['month'];?> <?php echo $date_array['mday'];?>, <?php echo $date_array['year'];?> Last Update: <?php echo $date_array['hours'];?>:<?php echo $date_array['minutes'];?>
			</div>
			  <div class="col-md-6 topmenu_links my_ac_drop_down">
					<? if(isset($_SESSION['user']['user_id']) && $_SESSION['user']['user_id']!=""){ $userid= base64_encode($_SESSION['user']['user_id']);?>
					<div class="btn-group " role="group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						My Account &nbsp;&nbsp;&nbsp;
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $baseUrl; ?>/users/videos-list">My Uploads</a><li>
							<li><a href="<?php echo $baseUrl; ?>/users/view-profile?uid=<? echo $userid; ?>">My Account</a><li>
							<li><a href="<?php echo $baseUrl; ?>/users/change-password">Change Password</a></li>
							<li><a href="<?php echo $baseUrl; ?>/users/logout">Sign Out</a></li>
						</ul>
					</div>
					<? } else{?>
					<ul class="list-inline">
						<li><a href="<?php echo $baseUrl; ?>/users/login">Sign In</a><li>
						<li>|<li>
						<li><a href="<?php echo $baseUrl; ?>/users/register">Sign Up</a></li>
					</ul>
					<? } ?>
			  </div>
		  </div>
	  </div>
  </div>
    <!-- Fixed navbar -->
    <nav class="navbar-default-custom-c navbar navbar-default navbar-fixed-top">
      <div class="container" style="position:relative">
	  <div class="ad_pos_ab"><img src="<?php echo $basePath; ?>/img/ad.jpg" alt="ads"/></div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
		  <a class="navbar-brand" href="<?php echo $baseUrl . '/'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Video Blogger" width="80%"/></h1></a>
        </div>
      </div>
    </nav>
<div class="latest_news alert mar_bnone">
	<div class="container pos_relative">
	<div class="close_lnews"><button type="button" class="close" data-dismiss="alert">×</button></div>
		<marquee behavior="scroll"  direction="left"  scrollamount="4">
		<ul class="list-inline">
			<?  foreach($topVideos as $key=>$videolinks){
					// if($key == 25){ break; }
				$video_id = base64_encode($videolinks->v_id);
			?>
				<li><a href="<?php echo $baseUrl; ?>/play-video?watch=<? echo $video_id;?>"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> <? echo $videolinks->v_title;?></a></li>	
			<? } ?>				
		</ul>
		</marquee>
	</div>
</div>
<div class="search_bar">
	<div class="container">
	<div class="row">
		<div class="col-md-3 filter_cate">
			<a href="<?php echo $baseUrl . '/'; ?>"><button type="button" class="home_icon"><span class="glyphicon glyphicon-home" style="color:#2fa4e7"></span></button></a>
			<div class="btn-group " role="group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				CATEGORIES &nbsp;&nbsp;&nbsp;
					<img  src="<?php echo $basePath; ?>/img/menu.png" alt="ads">
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<? if(isset($catData)){ foreach($catData as $key=>$catinfo){ 
							foreach($catinfo as $catid=>$catname){
								if(count( $catinfo )>1){
									$dropMenu = 'dropdown-submenu';
								}else{
									$dropMenu = '';
								}
								if($key == $catid){ ?>
									<li class ="<? echo $dropMenu; ?>" tabindex='-1'><a href="<?php echo $baseUrl; ?>/cat/<? echo $catid;?>"><? echo $catname;?></a>
										<ul class='dropdown-menu' role = 'menu'>
											<? foreach($catinfo as $catid=>$catname){ 
													if($key != $catid){	?>
														<li><a tabindex='-1' href="<?php echo $baseUrl; ?>/cat/<? echo $catid;?>"><? echo $catname;?></a></li>
											<? } } ?> 			
										</ul>										
									</li>
					<?php } } } }?>
				</ul>
			</div>
		</div>
		<div class="col-md-9 input_search">
			<div class="input-group">
			<input id="videosSearch" placeholder="Search for videos" class="form-control" type="textbox">
			<span class="input-group-btn">
			<button class="btn btn-default" onClick="searchByLocation();" type="button" id="addressSearch">Search</button>
			</span>
			</div>
		</div>
	</div>
	</div>
</div>
<script>
$(window).scroll(function() {
	if ($(this).scrollTop() > 150) {
		$('.search_bar').addClass('search_bar_fix_top');
	} else {
		$('.search_bar').removeClass('search_bar_fix_top');
	}
});
$('#videosSearch').keypress(function(e){
	if( e.keyCode == 13 ){
		searchByLocation();
	}
});
</script>