<style>
	#dddd{
		height:1100px;
	}
</style>
<div class="container min_height">
		<? if(isset($_GET['suc']) && $_GET['suc']=='reg'){?>
			<div class="alert alert-dismissible alert-success">
				<button type="button" class="close" data-dismiss="alert" onClick="reloadPageH()">×</button>
				<strong> Account verfication link, sent to your email id. Please click on that link and verify your account. </strong>
			</div>
		<? } ?>
	<div class="row">
		<div class="col-md-13">
		 <?php include('left-side-bar.phtml');?>
		</div>
		<div class="col-md-15">
			<div class="list-group cal_next">
				<a href="#" class="list-group-item active size18">
				Latest Videos
				</a>
			<div class="list_grou_itemspad">
				<div id="dddd">
					<?if(isset($this->vatTData) && count($this->vatTData)){
						foreach($this->vatTData as $links){
							$video_id = base64_encode($links->v_id);
						?>
						
						<a href="<?php echo $baseUrl; ?>/play-video?watch=<? echo $video_id;?>" class="list-group-item"><span class="glyphicon glyphicon-triangle-right cal_next" aria-hidden="true"></span><?php if(strlen($links->v_title)>55){echo substr($links->v_title,0,55) . '...'; }else{echo $links->v_title;}?></a>
						<?php }} else { ?>
							<br/>&nbsp;There are no links.
					<? }?>
				</div>
			</div>
			</div>
			<div align="center">
				<?php
					echo $this->paginationControl(
					$this->vatTData,
					'sliding',
					array('partial/paginator.phtml', 'Application'),
					array(
						'route' => 'cat',
						'id' =>$this->id
						)
					);
				?>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
			<div class="" align="center">
				<img  src="<?php echo $basePath; ?>/img/ads.png" alt="ads" width="100%">
			</div>
			</div>
			<?php include('right-side-bar.phtml');?>
			
		</div>
	</div>
</div>
<script>

$(document).ready(function(){
 $("#dddd").niceScroll({touchbehavior:false, cursorborder:"",cursorcolor:"#666",cursoropacitymax:0.6,cursorwidth:5,autohidemode: false});
});	
</script>
