<div class="container min_height">
	<div class="row">
		<div class="col-md-3">
		 <?php include('left-side-bar.phtml');?>
		</div>
		<div class="col-md-5">
			<div class="list-group cal_next">
				<a href="#" class="list-group-item active size18">
				Latest Videos
				</a>
				<div class="list_grou_itemspad">
				<a href="<?php echo $baseUrl; ?>/play-video" class="list-group-item"><span class="glyphicon glyphicon-triangle-right cal_next" aria-hidden="true"></span>Explain land acquisition in Andhra, ministers asks
				</a>
				<a href="#2" class="list-group-item"><span class="glyphicon glyphicon-triangle-right cal_next" aria-hidden="true"></span> Explain land acquisition in Andhra, ministers asks	
				</a>
				<a href="#3" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Explain land acquisition in Andhra, ministers asks
				</a>
				<a href="#4" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Explain land acquisition in Andhra, ministers asks
				</a>
				<a href="#5" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Explain land acquisition in Andhra, ministers asks
				</a>
				<a href="#6" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Morbi leo risus
				</a>
				<a href="#7" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Dapibus ac facilisis in
				</a>
				<a href="#8" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Morbi leo risus
				</a>
				<a href="#9" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Morbi leo risus
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Morbi leo risus
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Morbi leo risus
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Morbi leo risus
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span>  Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right cal_next" aria-hidden="true"></span> Dapibus ac facilisis in
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right cal_next" aria-hidden="true"></span> Morbi leo risus
				</a>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-triangle-right 
				" aria-hidden="true"></span> Dapibus ac facilisis in
				</a>
				
			</div>
			</div>
			<div align="center">
				<ul class="pagination">
					<li class="disabled"><a href="#">«</a></li>
					<li class="active"><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li><a href="#">5</a></li>
					<li><a href="#">6</a></li>
					<li><a href="#">»</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
			<div class="" align="center">
				<img  src="<?php echo $basePath; ?>/img/ads.png" alt="ads" width="100%">
			</div>
			</div>
			<?php include('right-side-bar.phtml');?>
			
		</div>
	</div>
</div>
