<div class="panel panel-default">
			<div class="panel-heading">Categories</div>
			<div class="">
				<ul class="nav">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Menu 2</a></li>
				<li><a href="#">Menu 3</a></li>
				<li><a href="#">Menu 4</a></li>
				<li><a href="#">Menu 5</a></li>
				<li><a href="#">Menu 6</a></li>
			  </ul>
			</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">Latest Videos</div>
				<div class="panel-body pad_bottom_0">
					<div class="row">
						<div class="col-xs-12 latest_videos">
							<ul class="latestvideos">
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb2.jpg" alt="ads"></td>
								</li>
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb3.jpg" alt="ads"></td>
								</li>
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb4.jpg" alt="ads"/></td>
								</li>
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb2.jpg" alt="ads"/></td>
								</li>
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb3.jpg" alt="ads"/></td>
								</li>
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb2.jpg" alt="ads"/></td>
								</li>
								<li class="news-item">
									<img  src="<?php echo $basePath; ?>/img/thumb4.jpg" alt="ads"/></td>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="panel-footer"> </div>
			</div>