<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];	
	$lastedVideos = $header->headerarray['lastedVideos'];	
?>
<div class="panel panel-default">
	<div class="panel-heading">Latest Videos</div>
	<div class="panel-body pad_bottom_0">
		<div class="row">
			<div class="col-xs-12 latest_videos">
				<ul class="latestvideos">
					<?php if(isset($lastedVideos)) { foreach($lastedVideos as $videoInfo){
						$video_id = base64_encode($videoInfo->v_id);
					?>
						<li class="news-item">
							<a href="<?php echo $baseUrl; ?>/play-video?watch=<? echo $video_id;?>"><img  src="<? echo $videoInfo->v_thumb_image;?>" alt="<? echo $videoInfo->v_title;?>"><div class="thumb_play_ico">
					<span class="glyphicon glyphicon glyphicon-play " aria-hidden="true"></span>
					</div></a>
						</li>									
					<?php } } ?>								
				</ul>
			</div>
		</div>
	</div>
	<div class="panel-footer"> </div>
</div>