<div class="panel panel-default">
	<div class="panel-heading">Categories</div>
	<div class="">
		<ul class="nav">
			<? if(isset($catData) && $catData!=''){ foreach($catData as $catinfo){?>
				<li><a href="<?php echo $baseUrl; ?>/cat/<? echo $catinfo->category_id;?>"><? echo $catinfo->category_name;?></a></li>
			<?php } }?>
		</ul>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">Latest Videos</div>
	<div class="panel-body pad_bottom_0">
		<div class="row">
			<div class="col-xs-12 latest_videos">
				<ul class="latestvideos">
					<?php foreach($vatData as $videoInfo){
						$video_id = base64_encode($videoInfo->v_id);
					?>
						<li class="news-item">
							<a href="<?php echo $baseUrl; ?>/play-video?watch=<? echo $video_id;?>"><img  src="<? echo $videoInfo->v_thumb_image;?>" alt="<? echo $videoInfo->v_title;?>"></a>
						</li>									
					<?php } ?>								
				</ul>
			</div>
		</div>
	</div>
	<div class="panel-footer"> </div>
</div>