<div class="container min_height">
	<div class="row">
	
		<div class="col-md-9">
		<div class="panel panel-default">
				<div class="panel-body">
				  <div class="col-md-3 well">

						<img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:140px;height:150px;">
				  </div>
					 <div class="col-md-9">
                    <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">First Name :</label>
                      <div class="col-sm-9">
                        Sfadda
                      </div>
                    </div>
					<div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Email:</label>
                      <div class="col-sm-8">
                        sfadda@gmail.com
                      </div>
                    </div>
				<div class="form-group row">
                      <label  class="col-sm-3 form-control-label" style="color:#828282">Phone Number:</label>
                      <div class="col-sm-4">
                        8500226782
                      </div>
					  <div class="col-sm-4">
					
					</div>
				</div>
				<div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">City:</label>
                      <div class="col-sm-8">
                       Hyderabad
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Face Book Profile Link:</label>
                      <div class="col-sm-8">
                       https://www.facebook.com/sfadda
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Message:</label>
                      <div class="col-sm-8">
                       Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio
                      </div>
                 </div>
				 <div class="form-group row">
                      <label class="col-sm-3 form-control-label" style="color:#828282">Skills:</label>
                      <div class="col-sm-8">
					  Art-director,Actor,Location-Rental
                        
                      </div>
                 </div>
                 </div>
				 <div class="col-md-12">
				 <div class="form-group row">
                      <label class="col-sm-4 form-control-label"><strong>Pics Upload:</strong></label>
                      <div class="col-sm-12">
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
						 <img alt="Keratam Telugu Full Movie | Rakul Preet Singh, Siddharth Raj Kumar | Sri Balaji Video" src="http://i.ytimg.com/vi/NqpamDXgXaE/default.jpg" style="width:120px;height:90px;"/>
                      </div>
                 </div>
				<div class="form-group row">
                      <label class="col-sm-4 form-control-label"><strong>Video links:</strong></label>
                  <div class="col-sm-12">
				  				
					<a href="http://localhost/video-collections/trunk/play-video?watch=OTM="><img alt="Greeku Veerudu Telugu Full Movie | Nagarjuna Akkineni | Nayantara | S Thaman" src="http://i.ytimg.com/vi/4gmGRztRSGQ/default.jpg">
						</a>		
									
					<a href="http://localhost/video-collections/trunk/play-video?watch=MTI5"><img alt="MR. Productions &amp; Nine Productions 'Two Side Love'" src="http://i.ytimg.com/vi/scTWs5F5Mn4/default.jpg"></a>		
									
					<a href="http://localhost/video-collections/trunk/play-video?watch=MTk0"><img alt=" Hello Brother Trailer || Telugu Short Film Trailer/ Teaser || by Ajay Ejjada || Creative Frames" src="http://i.ytimg.com/vi/qjlRu_99Z1A/default.jpg">
						</a>	
					<a href="http://localhost/video-collections/trunk/play-video?watch=OTM="><img alt="Greeku Veerudu Telugu Full Movie | Nagarjuna Akkineni | Nayantara | S Thaman" src="http://i.ytimg.com/vi/4gmGRztRSGQ/default.jpg">
					</a>
					<a href="http://localhost/video-collections/trunk/play-video?watch=OTM="><img alt="Greeku Veerudu Telugu Full Movie | Nagarjuna Akkineni | Nayantara | S Thaman" src="http://i.ytimg.com/vi/4gmGRztRSGQ/default.jpg">
					</a>
              </div>
                </div>
				 
		</div>
		</div>
		</div>
		
		</div>
		<div class="col-md-3">
			<img width="100%" alt="sfadda.com" src="http://localhost/video-collections/trunk/public/img/adsleft.jpg">				
		</div>
	</div>
</div>