<div class="container min_height">
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb4.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb2.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb2.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb3.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb1.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb1.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			<div class="panel panel-default hover_body">
				<div class="panel-body">
					<div class="media pos_r">
					<div class="pos_ab_btn">
					<button type="button" class="btn btn-primary btn-sm" >View More </button></div>
					<div class="media-left"> 
						<a href="#"><img class="img_pic" alt="" src="<?php echo $this ->basePath;?>public/img/thumb1.jpg" /> </a> 
					</div> 
					<div class="media-body" style="margin:0"> 
						<h4 class="media-heading"><a href="#">Name of person</a></h4>
						<p><span class="dim">City : </span> Hyderabad</p>
						<p><span class="dim">Industry : </span>Industry Name</p>
						<p><span class="dim">Skills :</span> Skills Name</p>	
					</div>
						<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus... <a href="#">More >></a></p>	
					</div>
				</div>
			</div>
			
			</div>
		<div class="col-md-4">
			<img width="100%" alt="sfadda.com" src="http://localhost/video-collections/trunk/public/img/adsleft.jpg">
		</div>
	</div>
		</div>
	</div>
</div>