<div class="login_ad_left smhide">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- rightbanner -->
	<ins class="adsbygoogle"
		 style="display:inline-block;width:300px;height:250px"
		 data-ad-client="ca-pub-9408213208791031"
		 data-ad-slot="6451237032"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<div class="login_ad_right smhide">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- rightbanner -->
	<ins class="adsbygoogle"
		 style="display:inline-block;width:300px;height:250px"
		 data-ad-client="ca-pub-9408213208791031"
		 data-ad-slot="6451237032"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<div class="container min_height">
  <div id="loginModal" class="show" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="alert alert-dismissible alert-success" style="display:none" id="sucessdiv">
		<strong id="sucessMsg"></strong>
</div>
<div class="alert alert-dismissible alert-danger" style="display:none" id="errordiv">
		<strong id="errorMsg"></strong>
	</div>
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Forget Password</h1>
      </div>
      <div class="modal-body">
		  <span id="errorMsg" style="color:red"></span>
          <form id="forgetForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <div class="pos_relative">
					<span class="error_msg_disp" id="emailError"></span>
			  <input type="text" id="forgetMail" name="forgetMail"  class="form-control" placeholder="Email">
            </div>
            </div>
            <div class="form-group">
              <button type="button" id="submit" class="btn btn-primary  btn-block" onclick="forgetPassword();">Submit</button>
			  <center><span id="reload"></span></center>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div><br/><br/>
  <div class="smhide"><center>
		<ins class="adsbygoogle"
			 style="display:inline-block;width:728px;height:90px"
			 data-ad-client="ca-pub-9408213208791031"
			 data-ad-slot="4974503839"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script></center>
	</div>
</div>
</div>
<script>
$('#forgetMail').keypress(function(e){
	if( e.keyCode == 13 ){
		forgetPassword();
	}
});
</script>
