<?php 
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
?>
<? if(isset($_SESSION['user']) && $_SESSION['user']!=""){?>
	<script>
		window.location = BASE_URL;
	</script>
<? }else{?>
 <div class="container min_height">
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="lrcontainer panel panel-default" style="padding:24px 20px 0px 20px;">
  <div class="login_input_h">
      <div class="title_h1">
          <h1 class="text-center">Welcome</h1>
		  <p class="text-center">Login with your Facebook, Google+ or Video blogger Account</p>
      </div>
	  <div class="socila_logins text-center">
	  <?php
		foreach ($this->options->getEnabledProviders() as $provider) {
		echo  $this->socialSignInButton($provider, $this->redirect,$basePath);
		}
		?>
		</div>
      <div class="">
          <form id="loginForm" class="form  center-block" method="POST">
            <div class="form-group">
				<div class="pos_relative">
					<span class="error_msg_disp" id="emailError"></span>
              <input type="text" class="form-control" id="email" name="email" placeholder="Email">
				</div>
            </div>
            <div class="form-group">
				<div class="pos_relative">
					<span class="error_msg_disp" id="passwordError"></span>
              <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            </div>
            <div class="form-group">
              <button type="button" class="btn btn-primary btn-block" onclick="loginValidations();">Sign In</button>
			  <center><span id="reload"></span></center>
            </div>
						<span id="errorMsg" style="color:red"></span>

			<div class="form-group">
				<span>Don't have an account <a href="<?php echo $baseUrl;?>/users/register" class="undeline">Register here</a></span>
				<span class="pull-right"><a href="<?php echo $baseUrl;?>/users/forgot-password" class="undeline">Forgot Password?</a></span>
			</div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>
</div> <!-- /container -->
<div class="login_ad_left smhide">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- leftbanner -->
	<ins class="adsbygoogle"
		 style="display:inline-block;width:120px;height:600px"
		 data-ad-client="ca-pub-9408213208791031"
		 data-ad-slot="7927970234"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<div class="login_ad_right smhide">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- leftbanner -->
	<ins class="adsbygoogle"
		 style="display:inline-block;width:120px;height:600px"
		 data-ad-client="ca-pub-9408213208791031"
		 data-ad-slot="7927970234"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<script>
$('#password').keypress(function(e){
	if( e.keyCode == 13 ){
		loginValidations();
	}
});
//$('body').css('overflow','hidden');
</script>
<? } ?>
