<div class="container  min_height ">
<div class="lrcontainer panel panel-default" style="padding:24px 20px 0px 20px;">
		<? $details=''; if(count($this->userDetails)){ foreach($this->userDetails as $detailss){ $details=$detailss;}}
			$dobex=''; if(isset($details->date_of_birth) && $details->date_of_birth!='') {
				$dob = $details->date_of_birth;
				$dobex = explode("/",$dob);
			}		
		?>
<div class="title_h1">
	<? if(isset($details->user_id) && $details->user_id!=''){ ?>
		<h1 class="text-center">Profile</h1>
	<? } else{?>
		<h1 class="text-center">Sign Up</h1>
	<? } ?>
</div>
<form  id="frm_meth" name="frm_meth" method="post" action="">	
	<div class="panel-default">		
		<div class="panel-body" id="tab_1_hide">
			<div class="form-horizontal">
				<div class="form-group">
					<div class="pos_relative">
					<span class="error_msg_disp" id="user_firstname_req"></span>
						<input type="text" class="form-control" id="user_first_name" placeholder="First Name" name="user_first_name" value="<? if(isset($details->display_name) && $details->display_name!='') {echo ucfirst($details->display_name);}else{}?>">
					</div>
				</div>
				<div class="form-group">
					<div class="pos_relative">
					<span class="error_msg_disp" id="user_lastname_req"></span>
						<input type="text" class="form-control" id="user_last_name" placeholder="Last Name" name="user_last_name" value="<? if(isset($details->last_name) && $details->last_name!='') {echo ucfirst($details->last_name);}else{}?>">
					</div>
				</div>				
				<div class="form-group">
					<div class="pos_relative">
						<span class="error_msg_disp" id="user_email_req"></span>
						<input type="email" class="form-control" id="user_email" placeholder="Email" name="user_email" value="<? if(isset($details->email) && $details->email!='') {echo $details->email;}else{}?>" <? if(isset($details->email) && $details->email!='') {?> readonly="readonly" <?}else{?> onmouseout="return checkEmailVaild();"<? } ?>>
					</div>
				</div>
				<input type="hidden" id="hidCheckValue" name="hidCheckValue" value='0'>
				<? if($details==""){?>
				<div class="form-group">
					<div class="pos_relative">
						<span class="error_msg_disp" id="user_pwd_req"></span>
						<input type="password" class="form-control" id="user_password" name="user_password" value="" placeholder="Password">
					</div>
				</div>
				<? } ?>
				<div class="form-group">
					<div class="pos_relative">
						<span class="error_msg_disp" id="user_mobile_req"></span>
						<input type="text" class="form-control" id="user_mobile" name="user_mobile" value="<? if(isset($details->contact_number) && $details->contact_number!='') {echo $details->contact_number;}else{}?>" placeholder="Your Mobile Number">
					</div>
				</div>
				<div class="form-group">
					<div class="pos_relative">
						<? if(isset($details->user_id) && $details->user_id!=''){ ?>
							<button type="button" class="btn btn-primary btn-block"  onCLick="validateReg();">Update</button>
						<? } else{?>
							<button type="button" class="btn btn-primary btn-block"  onCLick="validateReg();">Sign Up</button>
						<? } ?>
						
					</div>
				</div>
			</div>
		</div>
		<input type="hidden" id="hid_user_id" name="hid_user_id" value="<? if(isset($details->user_id) && $details->user_id!=''){ echo $details->user_id;}else{}?>">
		<input type="hidden" id="hid_ud_id" name="hid_ud_id" value="<? if(isset($details->ud_id) && $details->ud_id!=''){ echo $details->ud_id;}else{}?>">
		</form>			
		</div>
	</div>
	</div>