<?php 
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
?>
<div class="container  min_height ">
<div class="col-sm-8 panel " style="padding:24px 20px 0px 20px;">
	<? $details=''; if(count($this->userDetails)){ foreach($this->userDetails as $detailss){ $details=$detailss;}}
		$dobex=''; if(isset($details->date_of_birth) && $details->date_of_birth!='') {
			$dob = $details->date_of_birth;
			$dobex = explode("/",$dob);
		}		
	?>
<div class="title_h1">
	<? if(isset($details->user_id) && $details->user_id!=''){ ?>
		<h1 class="text-center">Profile</h1>
	<? } else{?>
		<h1 class="text-center well ">Sign Up</h1>
	<? } ?>
</div>
<script>
	$(document).ready(function(e) {
		refresh();
	});
</script>
<form  id="frm_meth" name="frm_meth" method="post" action="" enctype="multipart/form-data">	
	<div class="">		
		<div class="panel-body" id="tab_1_hide">
			<div class="form-horizontal">
				<div class="form-group">
					<div class="pos_relative">							
						<span class="glyphicon glyphicon-user btn-primary btn-lg"style="padding:9px 15px;"></span>	
						 <label class="btn btn-primary	 btn-file" style=" margin-bottom: 9px;">
							 <input type="file"  name="images[]" multiple="multiple">
						</label>
						<!--<label class="btn-file btn btn-primary">
						<input type="file" name="fileToUpload" id="image_file" class="form-control file_pad" style="height:auto">
						</label>	-->
						
					</div>
				</div>
				<div class="form-group">
					<div class="pos_relative">
					<span class="error_msg_disp" id="user_firstname_req"></span>
						<input type="text" class="form-control" id="user_first_name" placeholder="First Name" name="user_first_name" value="<? if(isset($details->display_name) && $details->display_name!='') {echo ucfirst($details->display_name);}else{}?>">
					</div>
				</div>
				<div class="form-group">
					<div class="pos_relative">
					<span class="error_msg_disp" id="user_lastname_req"></span>
						<input type="text" class="form-control" id="user_last_name" placeholder="Last Name" name="user_last_name" value="<? if(isset($details->last_name) && $details->last_name!='') {echo ucfirst($details->last_name);}else{}?>">
					</div>
				</div>				
				<div class="form-group">
					<div class="pos_relative">
						<span class="error_msg_disp" id="user_email_req"></span>
						<input type="email" class="form-control" id="user_email" placeholder="Email" name="user_email" value="<? if(isset($details->email) && $details->email!='') {echo $details->email;}else{}?>" <? if(isset($details->email) && $details->email!='') {?> readonly="readonly" <?}else{?> onmouseout="return checkEmailVaild();"<? } ?>>
					</div>
				</div>
				<input type="hidden" id="hidCheckValue" name="hidCheckValue" value='0'>
				<? if($details==""){?>
				<div class="form-group">
					<div class="pos_relative">
						<span class="error_msg_disp" id="user_pwd_req"></span>
						<input type="password" class="form-control" id="user_password" name="user_password" value="" placeholder="Password">
					</div>
				</div>
				<? } ?>
				<div class="form-group">
					<div class="pos_relative">				  
					<label class="c-input c-radio">
					  <input id="male" name="gender" type="radio" value="male" checked >
					  <span class="c-indicator"></span>
					  Male 
					</label>
					<label class="c-input c-radio">
					  <input id="female" name="gender" type="radio" value="female" >
					  <span class="c-indicator"></span>
					  Female
					</label>
					</div>
				</div>
				<div class="form-group">
					<div class="pos_relative">
						<span class="error_msg_disp" id="user_mobile_req"></span>
						<input type="text" class="form-control" id="user_mobile" name="user_mobile" value="<? if(isset($details->contact_number) && $details->contact_number!='') {echo $details->contact_number;}else{}?>" placeholder="Your Mobile Number">
					</div>
				</div>
				<? if(isset($details->user_id) && $details->user_id!=''){ 
				
				}else{?>
				<div class="form-group">
					   <div class="pos_relative">
                       <select name="city" id="city" class="form-control">
						<option value="">Select city</option>
					   <?php foreach($this->cities as $city){  ?>
						 <option value="<?php echo $city->c_id; ?>" ><?php echo ucfirst($city->c_name); ?></option>  
					  <?php  } ?>
                       </select>
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="c_ity" style="color:red;"></h6>
						</div>						
					</div>
                 </div>	
				 <div class="form-group">
                       <div class="pos_relative">
                       <select name="lang[]" id="lang" multiple="multiple" class="form-control">
						<option value="">Select languages</option>
						<?php 
							foreach($this->lang as $language){	
						?>
						<option value="<?php echo $language->lan_id; ?>"><?php echo ucfirst($language->lang_name); ?></option>
						<?php }?>
                       </select>
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="l_ang" style="color:red;"></h6>
						</div>
						
					</div>
                 </div>
				 <div class="form-group">
                       <div class="pos_relative">
						<select class="form-control" id="state_id" name="state_id[]" multiple="multiple" >
						<option value="" >Select skills</option>							
							<?php 							
								if(isset($this->allSkills)){
									foreach($this->allSkills as $skills){							
															
							?>				
								<option value="<?php echo $skills->u_c_id;?>">
								<?php echo $skills->u_category_name?></option>
							<?php } } ?>							
						</select>
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="s_kill" style="color:red;"></h6>
						</div>						
					</div>
                 </div>
				 <div class="form-group">
                      <div class="pos_relative">
                        <input type="text" class="form-control" value="" name="fb" id="fb" placeholder="Enter your facebook link">
                      </div>
					  <div class="col-sm-10">
						<div class="text-center">						
						<h6 id="f_b" style="color:red;"></h6>
						</div>						
					</div>
                 </div>
				 <div class="form-group">
                       <div class="pos_relative">
						 <label class="btn btn-primary	 btn-file">
							 <input type="file"  name="images[]" multiple="multiple">
						</label>
                      </div>
                 </div>
				 <input type="hidden" name="hid_value" id="hid_value" value="0">
				  <div class="form-group">
				  <div id="addmore">
				 <div class="row">
						<div class="col-xs-10">						
						<div class="my-form">   
							<p class="text-box">										
				<input type="text" class="form-control" value="" name="video[]" placeholder="link" id="video0"/>									
							<a style=" margin-left: 100%;position:absolute;margin-top:-7%;" href="javascript:void(0);" class="btn btn-primary" onclick="addMore()"> <span class="glyphicon glyphicon-plus"></span> </a>
							</p>
						<div class="clearfix"></div>
						</div>						
                      </div> 
                      </div> 
                      </div> 
                 </div> 
				<div style="width:100%">
					<div class="form-group" style="width:40%">					
						<div class="pos_relative">	
							<span class="error_msg_disp" id="user_captcha_req"></span>
							<input type="text" class="form-control" id="user_captcha" name="user_captcha" value="" placeholder="Enter Captcha">
						</div>
					</div>
					<div class="form-group" style=" margin-left: 40%;margin-right: 265px;margin-top: -59px;position: relative; width: 40%;">					
						<div class="pos_relative">	
							<input type="text" class="form-control" width="20px;" id="refreshCode" name="refreshCode" readonly="readonly" disabled="disabled"  value="">
							<img style=" margin-left: 105%;margin-top: -59px;position: relative;cursor: pointer; cursor: hand;" onCLick="refresh();" src="<?php echo $basePath;?>/img/refresh.png"  width="30px;" id="captch_find" alt="refresh"/>
						</div>
					</div>
				</div>
				<? } ?>	
				
				<div class="clearfix"></div>
				<div class="form-group">
					<div class="pos_relative">
						<? if(isset($details->user_id) && $details->user_id!=''){ ?>
							<button type="button" class="btn btn-primary btn-block"  onCLick="validateReg();">Update</button>
						<? } else{?>
							<button type="button" class="btn btn-primary btn-block"  onCLick="validateReg();">Sign Up</button>
						<? } ?>
						
					</div>
				</div>
			</div>
		</div>
		<input type="hidden" id="hid_user_id" name="hid_user_id" value="<? if(isset($details->user_id) && $details->user_id!=''){ echo $details->user_id;}else{}?>">
		<input type="hidden" id="hid_ud_id" name="hid_ud_id" value="<? if(isset($details->ud_id) && $details->ud_id!=''){ echo $details->ud_id;}else{}?>">
		</form>			
		</div>
	</div>
</div>
<!--<div class="login_ad_left smhide">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- leftbanner -->
	<!--<ins class="adsbygoogle"
		 style="display:inline-block;width:120px;height:600px"
		 data-ad-client="ca-pub-9408213208791031"
		 data-ad-slot="7927970234"></ins>
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<div class="login_ad_right smhide">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- leftbanner -->
	<!--<ins class="adsbygoogle"
		 style="display:inline-block;width:120px;height:600px"
		 data-ad-client="ca-pub-9408213208791031"
		 data-ad-slot="7927970234"></ins>-->
	<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<script>
	function addMore(){
	if($("#video"+$('#hid_value').val()).val()==""){
		alert("Required");
		$("#video"+$('#hid_value').val()).focus();
		return false;
	}else{
		var html ="";
		var value = parseInt($('#hid_value').val())+1;
		html +='<div id="dyDiv'+value+'"><label class="col-sm-3 form-control-label">&nbsp;&nbsp;</label>';
		html +='<div class="pos_relative"><div class="row">';
		html +='<div class="col-xs-10"><div class="my-form">';
		html +='<p class="text-box">';
		html +='<input type="text" class="form-control" value="" placeholder="link" name="video[]" id="video'+value+'">';
		html +='<a style=" margin-left: 100%;position:absolute;margin-top:-7%;" href="javascript:void(0);" class="btn btn-primary" onclick="delVideo('+value+')" ><span class="glyphicon glyphicon-minus"></span> </a>';
		html +='</p><div class="clearfix"></div></div></div></div></div></div>';
		$('#addmore').append(html);							
		$('#hid_value').val(value);
	}
}
function delVideo(value){
	if($("#video"+value).val()==""){
		$('#dyDiv'+value).remove();
		$('#hid_value').val(parseInt(value)-1);
	}else{
		if (confirm("Are you sure?")){
			$('#dyDiv'+value).remove();
			$('#hid_value').val(parseInt(value)-1);
		}
	}	
}
</script>
